import type { ArticleSection, BlogArticle } from "./blog-types.ts";

const section = (id: string, title: string, first: string, second: string): ArticleSection => ({
  id,
  title,
  blocks: [
    { type: "paragraph", html: first },
    { type: "paragraph", html: second },
  ],
});

const frigadeSources = [
  { label: "Frigade — Assist API", url: "https://frigade.com/assist-api" },
  { label: "Frigade — Assist API launch", url: "https://frigade.com/blog/your-product-cant-explain-itself" },
  { label: "Frigade — Pricing", url: "https://frigade.com/pricing" },
  { label: "Frigade — How it works", url: "https://frigade.com/how-it-works" },
];

const xRewardsSources = [
  { label: "X Help — Original Content Rewards", url: "https://help.x.com/en/using-x/original-content-rewards" },
  { label: "X Help — Creator Revenue Sharing", url: "https://help.x.com/en/using-x/creator-revenue-sharing" },
  { label: "TechCrunch — Original Content Rewards transition", url: "https://techcrunch.com/2026/08/08/x-replaces-misaligned-revenue-sharing-program-with-original-content-rewards/" },
];

const metaMuseSources = [
  { label: "Meta — Introducing Muse", url: "https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/" },
  { label: "Reuters — Meta launches Muse", url: "https://www.reuters.com/business/meta-launches-ai-agent-that-can-access-other-apps-send-emails-make-payments-2026-09-08/" },
  { label: "Axios — Meta debuts Muse", url: "https://www.axios.com/2026/09/08/meta-debuts-muse-personal-ai-agent" },
];

const aukSources = [
  { label: "Tencent-Hunyuan — AuK repository", url: "https://github.com/Tencent-Hunyuan/AuK" },
  { label: "Tencent-Hunyuan — AuK MIT license", url: "https://github.com/Tencent-Hunyuan/AuK/blob/main/LICENSE" },
  { label: "Tencent — AuK weights", url: "https://huggingface.co/tencent/AuK" },
  { label: "Tencent — AuK-Flash weights", url: "https://huggingface.co/tencent/AuK-Flash" },
];

export const approvedArticles20260909All: BlogArticle[] = [
  {
    status: "published",
    articleType: "main",
    cluster: "Frigade Assist API",
    targetSearchIntent: "Understand Frigade Assist API, current pricing, how its product-grounded agent tool works, security boundaries and launch limitations.",
    targetQuery: "Frigade Assist API",
    slug: "frigade-assist-api",
    title: "Frigade Assist API: Pricing, Features & How It Works",
    metaTitle: "Frigade Assist API: Pricing, Features & How It Works",
    metaDescription: "Frigade Assist API gives existing AI agents live product knowledge and in-app guidance. See how it works, current pricing, Vercel AI SDK setup and limits.",
    h1: "Frigade Assist API: Product-Grounded AI Agents Explained",
    excerpt: "Frigade Assist API lets an existing AI agent call Frigade as a specialized product-knowledge tool instead of replacing the agent's model or orchestration.",
    category: "Automation",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Frigade Assist API connecting an existing AI agent to live product knowledge and in-product guidance",
    sections: [
      section("what-launched", "What Frigade launched", "Frigade launched Assist API on September 8, 2026 for teams that already have an AI agent. The existing agent keeps its model, prompts and conversation logic, while Frigade is exposed as a callable tool for product-specific answers and in-product guidance.", "Frigade says its product-learning layer uses the software itself, not only static help-center text, and can relearn workflows after product changes. That relearning behavior is a vendor claim rather than an independently benchmarked accuracy guarantee."),
      section("integration", "How the integration works", "Frigade's current public example uses the Vercel AI SDK: the application's model decides when to invoke a Frigade guidance tool, then calls <code>frigade.assist</code> with the user and intent. Frigade says the approach is framework-agnostic for agents that support tool calling.", "This makes Assist API a product-expertise layer, not the general reasoning model for every message. Questions about the application UI, settings and multi-step workflows are the clearest fit; generic reasoning can remain with the existing agent."),
      section("pricing-security", "Pricing and security", "Frigade's current pricing page lists Growth starting at $1,000 per month, including five seats, two agents and 2,500 queries, with Enterprise priced separately. API access is listed on Growth and Enterprise, so teams should recheck current allowances before budgeting.", "Frigade documents SOC 2 Type II, GDPR compliance, TLS 1.2+ in transit, AES-256 at rest, PII scrubbing and enterprise options such as self-hosting and EU data residency. These are vendor-documented controls; regulated teams should still verify the current security package and data flows."),
      section("limits", "What is still unproven", "Public third-party evidence comparing Frigade's answer accuracy, workflow completion and relearning reliability is still limited. The launch material also does not justify inventing a universal latency SLA, undocumented rate limit or model-provider claim.", "For the implementation path, read <a href=\"/blog/how-to-use-frigade-assist-api\">How to Add Frigade Assist API to an Existing AI Agent</a>. The useful test is whether guidance stays correct across real product releases, roles and permission boundaries."),
    ],
    sources: frigadeSources,
    relatedPaths: ["/blog/how-to-use-frigade-assist-api"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Frigade Assist API",
    targetSearchIntent: "Add Frigade Assist API to an existing agent using the documented Vercel AI SDK-style tool pattern and validate permissions, routing and relearning.",
    targetQuery: "how to use Frigade Assist API",
    parentSlug: "frigade-assist-api",
    slug: "how-to-use-frigade-assist-api",
    title: "How to Add Frigade Assist API to an Existing AI Agent",
    metaTitle: "How to Use Frigade Assist API with an Existing AI Agent",
    metaDescription: "A practical Frigade Assist API setup guide for existing AI agents, including the Vercel AI SDK tool pattern, product access, testing and safety checks.",
    h1: "How to Add Frigade Assist API to an Existing AI Agent",
    excerpt: "The safest Frigade integration keeps the existing agent in control and gives Frigade a narrow, testable role for product-specific guidance.",
    category: "Automation",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Existing AI agent calling Frigade Assist API for product-specific guidance",
    sections: [
      section("prepare", "Prepare Frigade and your agent", "Start with an agent that already supports tool or function calling and a Frigade account that can learn the product workflows you want to support. Use a dedicated product account with the minimum permissions needed rather than an all-powerful training account.", "Frigade's public material says its agents navigate the product and can combine that learned workflow knowledge with connected knowledge sources. Test the important workflows yourself rather than treating automatic relearning as proven."),
      section("register-tool", "Register Frigade as a narrow tool", "Frigade's launch example imports <code>@frigade/ai-sdk</code>, registers a tool inside a Vercel AI SDK <code>streamText</code> flow and executes <code>frigade.assist({ userId, intent })</code>. Use Frigade's live documentation for exact package and credential setup.", "Give the tool a narrow description: call it for product-specific questions, settings and guided workflows. Do not route every conversation through Frigade when the existing model can answer without product context."),
      section("permissions-tests", "Test identity, permissions and updates", "Pass the correct user identity and test at least two roles with different permissions. A standard member should not receive administrative guidance or actions that the product itself would not allow.", "Build an evaluation set from real questions, then repeat it after moving a setting or changing a controlled workflow. That directly tests Frigade's relearning claim against your own release process."),
      section("observe", "Watch usage and production behavior", "Frigade's Growth plan currently starts at $1,000 per month with 2,500 queries, so tool-routing quality affects both cost and user experience. Track when the tool was called, what it returned and whether the user completed the intended workflow.", "Start with guidance-only or reversible tasks and expand autonomy only after the results are stable. For product scope, pricing and security boundaries, return to the <a href=\"/blog/frigade-assist-api\">Frigade Assist API overview</a>."),
    ],
    sources: frigadeSources,
    relatedPaths: ["/blog/frigade-assist-api"],
  },
  {
    status: "published",
    articleType: "main",
    cluster: "X Original Content Rewards",
    targetSearchIntent: "Understand X Original Content Rewards rollout, eligibility, qualified impressions, originality rules, application path and payout boundaries.",
    targetQuery: "X Original Content Rewards",
    slug: "x-original-content-rewards",
    title: "X Original Content Rewards: Eligibility, Rules & How to Apply",
    metaTitle: "X Original Content Rewards: Eligibility, Rules & How to Apply",
    metaDescription: "X Original Content Rewards replaces Creator Revenue Sharing. See the September 2026 rollout, eligibility rules, qualified impressions, originality requirements and application process.",
    h1: "X Original Content Rewards: Eligibility, Qualified Impressions & Rollout",
    excerpt: "X Original Content Rewards replaces Creator Revenue Sharing with a monetization program centered on original work and qualified Premium-user Home Timeline impressions.",
    category: "Social Media",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "X Original Content Rewards eligibility and rollout graphic with original content and qualified impressions",
    sections: [
      section("rollout", "What changed in September 2026", "X ended Creator Revenue Sharing accrual after September 7, 2026 and says application access for Original Content Rewards began rolling out to existing Revenue Sharing members on September 8. Rollout is gradual, so otherwise eligible accounts may not see the application simultaneously.", "The replacement program rewards original posts based on qualified impressions rather than publishing a fixed universal earnings-per-view formula. X says the old program's final eligible payout is expected around September 11."),
      section("eligibility", "Current application requirements", "X currently requires applicants to be in a supported country, be at least 18, have an account in good standing, use a Personal or Business Account, hold Premium, Premium+ or Premium Business, have at least 500 verified followers, and have at least 500,000 verified-user Home Timeline impressions in the previous 90 days.", "India is currently listed as supported. Reply impressions are excluded from the 500,000 application threshold, and meeting the published thresholds lets a creator apply but does not guarantee acceptance."),
      section("qualified-original", "Qualified impressions and original content", "X defines a qualified impression as a unique Home Timeline impression from a Premium-tier viewer where at least 50% of the post is visible. Repeat, paid or promoted, artificial and fraudulent impressions are excluded.", "Original content includes work the creator writes, films, designs or produces and meaningful commentary that adds genuine perspective or expertise. Reposts and minimal cosmetic edits do not become original merely because they are uploaded again."),
      section("payments", "Application and payout boundaries", "X directs eligible creators to Creator Studio → Original Content Rewards. Its current help material says applications are reviewed, and payouts are issued every two weeks subject to eligibility; a minimum payout threshold of $30 is currently documented.", "X does not publish a universal fixed payout rate, so the 500,000-impression threshold is not an earnings calculator. See <a href=\"/blog/how-to-apply-x-original-content-rewards\">the application guide</a> and <a href=\"/blog/x-original-content-qualified-impressions\">the originality and qualified-impression guide</a> for the two distinct practical intents."),
    ],
    sources: xRewardsSources,
    relatedPaths: ["/blog/how-to-apply-x-original-content-rewards", "/blog/x-original-content-qualified-impressions"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "X Original Content Rewards",
    targetSearchIntent: "Check X Original Content Rewards eligibility and apply through Creator Studio during the September 2026 rollout.",
    targetQuery: "how to apply for X Original Content Rewards",
    parentSlug: "x-original-content-rewards",
    slug: "how-to-apply-x-original-content-rewards",
    title: "How to Apply for X Original Content Rewards",
    metaTitle: "How to Apply for X Original Content Rewards: Eligibility Guide",
    metaDescription: "Check whether you qualify for X Original Content Rewards and how to apply in Creator Studio, including follower, impression, Premium and rollout requirements.",
    h1: "How to Apply for X Original Content Rewards",
    excerpt: "Application access is rolling out through Creator Studio, but creators should verify country, Premium plan, follower and qualified-impression requirements first.",
    category: "Social Media",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "How to apply for X Original Content Rewards eligibility checklist",
    sections: [
      section("requirements", "Check the hard requirements first", "Confirm that your country is supported, you are at least 18, the account is in good standing and you use a Personal or Business Account. Political and government organization accounts are excluded under the current rules.", "Applicants currently need Premium, Premium+ or Premium Business, at least 500 verified followers and at least 500,000 verified-user Home Timeline impressions over the previous 90 days. Premium Basic is not listed as an applicant subscription even though Basic viewers can contribute qualified impressions."),
      section("studio", "Open Creator Studio", "X directs creators to Creator Studio → Original Content Rewards to see current eligibility and application status. If the option is missing during rollout, recheck the account requirements and try again later rather than assuming permanent rejection.", "If you previously completed identity verification and payout setup for Creator Revenue Sharing, X says those steps do not need to be repeated solely because of the program transition, but verify that the displayed information is current."),
      section("review", "Submit and understand review", "Meeting the published thresholds permits an application; it does not guarantee approval. X's current help material says it reviews applications, so use the live help page rather than third-party promises about approval timing.", "If unsuccessful, follow X's stated appeal or reapplication process instead of trying to bypass monetization controls. The account must continue complying with the program and platform rules after acceptance."),
      section("not-showing", "If Original Content Rewards is not showing", "Recheck the country list, Premium plan, verified-follower count, verified-user Home Timeline impressions, account standing and whether your account is included in the current rollout population. Do not infer eligibility from public post-view counts alone.", "For the full program rules, read the <a href=\"/blog/x-original-content-rewards\">Original Content Rewards overview</a>. For exactly what X counts as original and qualified, use the <a href=\"/blog/x-original-content-qualified-impressions\">policy guide</a>."),
    ],
    sources: xRewardsSources,
    relatedPaths: ["/blog/x-original-content-rewards", "/blog/x-original-content-qualified-impressions"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "X Original Content Rewards",
    targetSearchIntent: "Understand what X treats as original content and which impressions qualify for Original Content Rewards.",
    targetQuery: "what counts as original content on X",
    parentSlug: "x-original-content-rewards",
    slug: "x-original-content-qualified-impressions",
    title: "What Counts as Original Content and Qualified Impressions on X?",
    metaTitle: "X Original Content Rules & Qualified Impressions Explained",
    metaDescription: "See what X considers original content for Original Content Rewards and how qualified impressions differ from ordinary views, reposts and promoted traffic.",
    h1: "What Counts as Original Content and Qualified Impressions on X?",
    excerpt: "X applies two separate tests: whether a creator made genuinely original work and whether each impression satisfies the program's qualified-impression rules.",
    category: "Social Media",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "X Original Content Rewards originality and qualified impression rules explained",
    sections: [
      section("original", "What counts as original content", "X says original content is work a creator personally writes, films, designs or produces that reflects their own voice, perspective, expertise or creativity. Text, Articles, images, video, design and reporting can all qualify.", "Commentary can also qualify when it adds meaningful analysis, context or expertise. A cosmetic crop, border, watermark or speed change does not automatically turn someone else's work into original content."),
      section("rights", "Originality does not replace rights", "Program originality and copyright are separate. Even a transformative or analytical post can still create intellectual-property problems if the creator lacks the right to use underlying material.", "The safest strategy is to make the creator's own reporting, footage, analysis, design or expertise the core value rather than attempting to discover the minimum edit needed to reuse another person's content."),
      section("qualified", "What is a qualified impression", "X currently defines a qualified impression as a unique Home Timeline impression from a Premium-tier user where at least 50% of the post is visible. Repeat impressions from the same account on the same post do not count again.", "Paid or promoted impressions, artificial impressions and fraudulent impressions are excluded. X also excludes reply impressions from the 500,000 verified-user Home Timeline threshold used for application eligibility."),
      section("measure", "Measure the right thing", "Public view counts are not a substitute for Creator Studio monetization metrics because the program filters both the viewer and the placement. The 500,000 threshold is an application requirement, not a published payout formula.", "For application steps, see <a href=\"/blog/how-to-apply-x-original-content-rewards\">How to Apply for X Original Content Rewards</a>. For the full transition and payout boundaries, return to the <a href=\"/blog/x-original-content-rewards\">main program guide</a>."),
    ],
    sources: xRewardsSources,
    relatedPaths: ["/blog/x-original-content-rewards", "/blog/how-to-apply-x-original-content-rewards"],
  },
  {
    status: "published",
    articleType: "main",
    cluster: "Meta Muse",
    targetSearchIntent: "Understand Meta Muse as a consumer personal AI agent: capabilities, US rollout, surfaces, permissions, security architecture, pricing state and limitations.",
    targetQuery: "Meta Muse",
    slug: "meta-muse-ai-agent",
    title: "Meta Muse AI Agent: Features, Availability, Pricing & How It Works",
    metaTitle: "Meta Muse AI Agent: Features, Availability & Pricing",
    metaDescription: "Meta launched Muse on September 8, 2026. See what the personal AI agent can do, where it is available, WhatsApp access, paid-tier reporting, privacy and limits.",
    h1: "Meta Muse: Meta’s Personal AI Agent Explained",
    excerpt: "Meta Muse is a US-first personal AI agent that can work across apps and the web, continue long-running tasks and request approval before sensitive actions.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Meta Muse personal AI agent with secure virtual machine, connected apps and approval controls",
    sections: [
      section("launch", "What Meta launched", "Meta launched Muse on September 8, 2026 as a personal AI agent rather than a conventional answer-only chatbot. Meta says Muse can browse, fill forms, send email with approval, plan and book travel, continue long-running work after the app closes and make supported purchases.", "At launch Meta says Muse is rolling out in the United States through iOS, Android, muse.ai and WhatsApp, with AI-glasses support planned. No verified India or worldwide rollout date was announced in the launch post."),
      section("permissions", "Apps, approvals and payments", "Users choose which services Muse connects to and how much access it receives. Meta gives email as an example where read access can be granted without send access, while sensitive actions such as sending or purchasing require approval.", "Meta says supported checkout can use Stripe Link and a one-time-use card, with Shop Pay and 1Password integrations planned later. Treat future integrations as future until they appear in the live product."),
      section("security-pricing", "Security architecture and pricing", "Meta says Muse runs inside a dedicated Muse Secure VM with a separate Sentinel agent enforcing internet and service access, isolated credential storage, an audit trail and controls for memory and model-training opt-out. Those are first-party architecture claims, not a guarantee that errors cannot occur.", "Meta's launch post says most use is free and paid plans are available for heavier use. Reuters reports subscription tiers at $20 and $100 per month; because Meta's launch page does not publish a complete public quota table, verify current in-product billing before purchase."),
      section("limits", "Important launch boundaries", "Reuters reported pre-launch internal testing issues, while Meta says the delayed launch improved safety and that the public system met its launch thresholds. That reporting is relevant context but not proof that every pre-launch issue persists in the public release.", "For practical setup, read <a href=\"/blog/how-to-use-meta-muse\">How to Use Meta Muse</a>. For the Secure VM, Sentinel, credentials and data controls, use the <a href=\"/blog/meta-muse-privacy-safety\">Meta Muse privacy and safety guide</a>."),
    ],
    sources: metaMuseSources,
    relatedPaths: ["/blog/how-to-use-meta-muse", "/blog/meta-muse-privacy-safety"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Meta Muse",
    targetSearchIntent: "Access Meta Muse on its current US surfaces, connect services with least privilege, approve sensitive actions and troubleshoot rollout access.",
    targetQuery: "how to use Meta Muse",
    parentSlug: "meta-muse-ai-agent",
    slug: "how-to-use-meta-muse",
    title: "How to Use Meta Muse on App, Web & WhatsApp",
    metaTitle: "How to Use Meta Muse on App, Web & WhatsApp",
    metaDescription: "Learn how to access Meta Muse in the US, use it on iOS, Android, web or WhatsApp, connect services safely, approve actions and troubleshoot rollout access.",
    h1: "How to Use Meta Muse: App, Web, WhatsApp & Permissions",
    excerpt: "Start Muse with a bounded task, connect only the services it needs and use the approval and audit controls before increasing its autonomy.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Meta Muse access across app, web and WhatsApp with connected-service permission controls",
    sections: [
      section("access", "Check access and choose a surface", "Meta's confirmed launch is US-first on iOS, Android, muse.ai and WhatsApp. Outside the United States, a missing Muse option should first be treated as a rollout limitation because Meta has not announced a verified India or global launch date.", "Use official Meta surfaces rather than unofficial apps or extensions. Rollouts can be gradual, so availability may differ by account and surface even within a supported market."),
      section("start", "Start with a bounded task", "Begin with a reversible job such as researching travel options, preparing a grocery list or drafting an email instead of immediately combining broad account access with payments and irreversible actions.", "Connect only the services required for the task. Prefer read-only access when action permissions are unnecessary, and revoke integrations that are no longer useful."),
      section("approve", "Review approvals and the audit trail", "Meta says Muse asks for approval before sensitive actions such as sending email or making purchases. Check the recipient, amount, merchant, dates and form details rather than treating approval as a routine click.", "Muse can keep working after the app closes, so use its audit trail to verify what it completed and what it still plans to do. Long-running autonomy makes post-task review important."),
      section("troubleshoot", "If Muse is not showing", "Check the confirmed market, app version, account rollout state and any separate service login or permission step. Meta has not published a universal waitlist or exact per-account schedule, so avoid unofficial unlock services.", "For product capabilities and pricing context, return to the <a href=\"/blog/meta-muse-ai-agent\">Meta Muse overview</a>. For credentials, Sentinel and privacy controls, read <a href=\"/blog/meta-muse-privacy-safety\">Meta Muse Privacy & Safety</a>."),
    ],
    sources: metaMuseSources,
    relatedPaths: ["/blog/meta-muse-ai-agent", "/blog/meta-muse-privacy-safety"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Meta Muse",
    targetSearchIntent: "Evaluate Meta Muse security and privacy architecture, permissions, credentials, approvals, memory and training controls, and independently reported launch concerns.",
    targetQuery: "is Meta Muse safe",
    parentSlug: "meta-muse-ai-agent",
    slug: "meta-muse-privacy-safety",
    title: "Meta Muse Privacy & Safety: Secure VM, Sentinel & Data Controls",
    metaTitle: "Meta Muse Privacy & Safety: Secure VM & Sentinel",
    metaDescription: "How Meta Muse handles permissions, passwords, payments, memory and training data, plus what Secure VM and Sentinel do and what independent reporting found.",
    h1: "Is Meta Muse Safe? Privacy, Secure VM & Sentinel Explained",
    excerpt: "Muse combines a dedicated Secure VM, separate Sentinel enforcement, credential separation, approvals and auditability, but users should still grant access conservatively.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Meta Muse Secure VM and Sentinel privacy architecture with permissions and audit trail",
    sections: [
      section("vm", "Muse Secure VM and Sentinel", "Meta says each Muse runs in a dedicated cloud computer called Muse Secure VM. A separate Sentinel agent is isolated from Muse and, according to Meta, controls whether Muse can reach the internet or connected services and requests user permission where required.", "This is a stronger security model than letting the acting agent decide its own boundaries, but it remains a vendor-described architecture rather than independent proof of perfect isolation or reliability."),
      section("credentials", "Credentials and least privilege", "Meta says Muse cannot directly see underlying passwords or payment details; credentials are stored separately so the agent can use them without exposing the secret. Users also choose which apps to connect and what permission level each gets.", "Use least privilege anyway: grant read-only access when possible, add write or purchase access only for workflows that need it, and disconnect integrations that no longer serve a purpose."),
      section("data", "Memory, training and payments", "Meta says users can tell Muse to forget remembered information, can opt out of having Muse interactions used to train Meta AI models, and that Muse conversations and VM data are not shared with its advertising systems.", "For supported checkout Meta says Stripe Link can issue a one-time-use card. That can reduce card exposure to merchants but does not remove the need to review merchant, amount, address and terms before approval."),
      section("evidence", "Independent reporting and future features", "Reuters reported pre-launch testing problems including disconnections and unexpected handling of personal material; Meta says the delayed launch was used to improve safety and the public release met its minimum thresholds. Treat both statements in context rather than turning either into a universal conclusion.", "Meta says a more private Confidential VM design is planned later in 2026, so it should not be described as available today. For access and permission setup, see <a href=\"/blog/how-to-use-meta-muse\">How to Use Meta Muse</a>, and return to the <a href=\"/blog/meta-muse-ai-agent\">main Muse guide</a> for product scope."),
    ],
    sources: metaMuseSources,
    relatedPaths: ["/blog/meta-muse-ai-agent", "/blog/how-to-use-meta-muse"],
  },
  {
    status: "published",
    articleType: "main",
    cluster: "Tencent AuK / AuK-Flash",
    targetSearchIntent: "Understand Tencent AuK and AuK-Flash release status, supported speech tasks, local tooling, license, availability and current limitations.",
    targetQuery: "Tencent AuK",
    slug: "tencent-auk-speech-model",
    title: "Tencent AuK: Open-Source Speech Model, AuK-Flash & Local Setup",
    metaTitle: "Tencent AuK: Open-Source Speech Model & AuK-Flash Guide",
    metaDescription: "Tencent open-sourced AuK and AuK-Flash for TTS, speech editing, enhancement and separation. See features, local setup, ComfyUI support, license and limits.",
    h1: "Tencent AuK: Open-Source Speech Generation and Editing Model",
    excerpt: "Tencent AuK is a 1.5B open-source speech generation and editing family with a Base checkpoint and a four-step AuK-Flash variant.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Tencent AuK and AuK-Flash speech generation and editing workflow with waveform operations",
    sections: [
      section("release", "What Tencent released", "Tencent-Hunyuan open-sourced AuK on September 9, 2026, with code and public model weights for the 1.5B Base model and AuK-Flash. Tencent describes Flash as a distilled checkpoint for fixed four-step inference.", "The repository includes CLI and Python inference, Gradio, official ComfyUI integration, prompt-enhancer tooling and a fine-tuning pipeline. A local Python interface is not the same thing as a hosted commercial API; no universal managed API price is documented in the release."),
      section("tasks", "One interface for many speech tasks", "AuK exposes zero-shot and instruction TTS, speech-content and lyric editing, pitch, speed and volume changes, emotion and timbre edits, de-accenting, nonverbal edits, whisper conversion, enhancement, speech and music separation, and target-speaker extraction through natural-language instructions.", "That breadth is a documented capability list, not an independent quality ranking. Listening quality, identity preservation, language coverage and artifact rates still need task-specific evaluation."),
      section("local-license", "Local setup and license", "Tencent documents Python 3.10 and separate downloads for AuK or AuK-Flash plus Qwen2.5-Omni-3B as the MLLM encoder. The diffusion checkpoint, encoder and VAE are separate runtime pieces, and Tencent does not publish one universal minimum-VRAM requirement.", "The repository license explicitly applies MIT terms to the publicly released training code, inference code, parameters and weights. Teams should still review required dependency licenses and exercise consent and rights controls for voice cloning or transformation."),
      section("guides", "Choose the right practical guide", "For installation and weights, use <a href=\"/blog/run-tencent-auk-locally\">How to Run Tencent AuK Locally</a>. For task design, use the <a href=\"/blog/tencent-auk-speech-editing-guide\">speech editing workflow guide</a>.", "Creators who prefer nodes can use the <a href=\"/blog/tencent-auk-comfyui-guide\">official ComfyUI integration guide</a>. Tencent currently documents a 30-second source-plus-target sequence limit for that ComfyUI integration, so do not generalize it into a permanent model-wide duration limit."),
    ],
    sources: aukSources,
    relatedPaths: ["/blog/run-tencent-auk-locally", "/blog/tencent-auk-speech-editing-guide", "/blog/tencent-auk-comfyui-guide"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Tencent AuK / AuK-Flash",
    targetSearchIntent: "Install Tencent AuK or AuK-Flash locally with official weights, Python 3.10, CLI or Gradio and cautious hardware planning.",
    targetQuery: "how to run Tencent AuK locally",
    parentSlug: "tencent-auk-speech-model",
    slug: "run-tencent-auk-locally",
    title: "How to Run Tencent AuK Locally: Install, AuK-Flash & Weights",
    metaTitle: "How to Run Tencent AuK Locally: Install & AuK-Flash Setup",
    metaDescription: "Install Tencent AuK or AuK-Flash locally with official weights, Python 3.10, CLI or Gradio. Includes model files, setup steps and hardware cautions.",
    h1: "How to Run Tencent AuK Locally",
    excerpt: "Tencent documents a Python 3.10 local workflow with separate AuK, optional AuK-Flash and Qwen2.5-Omni-3B downloads.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Tencent AuK Base, AuK-Flash and Qwen encoder local installation flow",
    sections: [
      section("choose", "Choose Base or AuK-Flash", "Use AuK Base for the configurable quality-focused path and AuK-Flash when you want Tencent's fixed four-step distilled checkpoint. Actual latency still depends on hardware, duration and the rest of the runtime.", "Do not convert the four-step design into an unsupported universal real-time claim. Benchmark both variants on the exact speech task you plan to ship."),
      section("install", "Install the official environment", "Tencent documents cloning <code>Tencent-Hunyuan/AuK</code>, creating a Python 3.10 environment with uv or Conda and installing the repository. Optional extras add Gradio, ComfyUI or fine-tuning dependencies.", "Install a platform-appropriate PyTorch stack when needed, then use the live repository instructions rather than pinning a launch-day dependency version in perpetuity."),
      section("weights", "Download the required weights", "The official Hugging Face path downloads <code>tencent/AuK</code> for Base, <code>tencent/AuK-Flash</code> for Flash and <code>Qwen/Qwen2.5-Omni-3B</code> as the encoder. The expected checkpoint layout keeps these as separate directories.", "Text-encoder keys can appear absent from the diffusion checkpoint because the encoder is loaded separately. Do not treat that documented separation as a corrupt checkpoint."),
      section("hardware", "Run and plan hardware cautiously", "The CLI always uses a natural-language instruction and can add source or reference audio depending on the task. Gradio is available through the documented optional extra, while Prompt Enhancer requires an OpenAI-compatible LLM configuration.", "Tencent does not publish one universal minimum-VRAM number, so measure memory with your dtype, loaded variant and audio duration. For task coverage and licensing, return to the <a href=\"/blog/tencent-auk-speech-model\">main AuK guide</a>; for node workflows see <a href=\"/blog/tencent-auk-comfyui-guide\">the ComfyUI guide</a>."),
    ],
    sources: aukSources,
    relatedPaths: ["/blog/tencent-auk-speech-model", "/blog/tencent-auk-comfyui-guide", "/blog/tencent-auk-speech-editing-guide"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Tencent AuK / AuK-Flash",
    targetSearchIntent: "Use AuK's natural-language interface for TTS, content edits, enhancement, paralinguistic changes and source-separation workflows.",
    targetQuery: "Tencent AuK speech editing",
    parentSlug: "tencent-auk-speech-model",
    slug: "tencent-auk-speech-editing-guide",
    title: "Tencent AuK Speech Editing Guide: TTS, Enhancement & Separation",
    metaTitle: "Tencent AuK Speech Editing Guide: TTS, Cleanup & Separation",
    metaDescription: "Learn how Tencent AuK handles TTS, speech edits, enhancement, emotion and timbre changes, and source separation through natural-language instructions.",
    h1: "Tencent AuK Speech Editing and Voice Workflow Guide",
    excerpt: "AuK exposes a wide range of speech-generation and editing jobs through one instruction interface, so the useful way to evaluate it is workflow by workflow.",
    category: "Creator Tools",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "Tencent AuK waveform before-and-after workflow for TTS, editing, enhancement and separation",
    sections: [
      section("tts", "TTS and speech-content editing", "Zero-shot TTS uses reference audio plus target text, while instruction TTS can generate from a voice description without a reference clip. Voice cloning should only use reference voices for which the operator has appropriate consent and rights.", "Speech-content editing changes what is said inside an existing recording. For creator work, verify timing, speaker consistency and artifacts before replacing the original take."),
      section("acoustic", "Acoustic and paralinguistic edits", "Tencent documents pitch, speed and volume edits as well as emotion, timbre, de-accenting, nonverbal-sound changes and whisper conversion. Start with one transformation at a time so failures are easier to diagnose.", "A documented task is not a promise of studio-quality output for every language, speaker or recording condition. Human listening review remains essential for consequential work."),
      section("enhance", "Enhancement and separation", "AuK supports denoising, dereverberation, speech separation, music separation and target-speaker extraction. That gives the same family roles often handled by dedicated restoration and source-separation systems.", "Independent matched comparisons against specialist tools are still sparse, so do not assume AuK is best-in-class at every supported task simply because the interface is broad."),
      section("workflow", "A safer creator workflow", "Keep the original recording, make the smallest necessary edit, apply cleanup or paralinguistic transformations separately, compare against the source and retain an edit log for client or high-stakes work.", "For setup use <a href=\"/blog/run-tencent-auk-locally\">the local AuK guide</a>; for node-based work use <a href=\"/blog/tencent-auk-comfyui-guide\">the ComfyUI guide</a>; and return to the <a href=\"/blog/tencent-auk-speech-model\">main overview</a> for release and license details."),
    ],
    sources: aukSources,
    relatedPaths: ["/blog/tencent-auk-speech-model", "/blog/run-tencent-auk-locally", "/blog/tencent-auk-comfyui-guide"],
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Tencent AuK / AuK-Flash",
    targetSearchIntent: "Install Tencent's official AuK ComfyUI nodes and use Base or AuK-Flash for node-based speech generation, editing, enhancement and separation.",
    targetQuery: "Tencent AuK ComfyUI",
    parentSlug: "tencent-auk-speech-model",
    slug: "tencent-auk-comfyui-guide",
    title: "Tencent AuK ComfyUI Guide: Install Nodes & Build Speech Workflows",
    metaTitle: "Tencent AuK ComfyUI Guide: Install Nodes & Workflow",
    metaDescription: "Use Tencent AuK and AuK-Flash in ComfyUI for TTS, speech editing, enhancement and separation. Follow the official node and workflow setup.",
    h1: "Tencent AuK ComfyUI Guide",
    excerpt: "Tencent ships an official ComfyUI integration with AuK Model Loader and Generate/Edit nodes, plus a reusable workflow.",
    category: "Creator Tools",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-09",
    dateModified: "2026-09-09",
    ogAlt: "ComfyUI-style Tencent AuK Model Loader to Generate or Edit node workflow with Base and Flash choice",
    sections: [
      section("official", "Use the official integration", "Tencent's repository includes ComfyUI-AuK, an AuK Model Loader and AuK Generate/Edit nodes with a reusable workflow. That means creators do not need an unofficial node pack merely to access the newly released model.", "Install AuK's documented <code>.[comfyui]</code> extra and place or link the included node package into the ComfyUI custom-nodes path according to Tencent's live guide."),
      section("weights", "Load Base, Flash and the encoder", "Use the same checkpoint layout as the local setup: AuK Base or optional AuK-Flash plus Qwen2.5-Omni-3B. Confirm each configured path separately before treating a load failure as a model bug.", "Base is the configurable path; Flash is Tencent's four-step distilled variant. Compare them on the same source audio rather than assuming the faster path always gives the best result."),
      section("workflow", "Build the speech workflow", "AuK chooses the job from the natural-language instruction, so the same node workflow can be adapted to TTS, content editing, enhancement or separation when the required audio input is supplied.", "Prompt Enhancer is optional and requires an OpenAI-compatible LLM configuration. Leave it disabled initially when you want to distinguish raw model behavior from instruction-rewriting behavior."),
      section("limits", "Current ComfyUI limits and troubleshooting", "Tencent's current documentation states a 30-second source-plus-target sequence limit for the ComfyUI integration. Treat that as today's integration constraint, not a permanent model-wide duration claim.", "If memory is tight, load one variant at a time and avoid quoting unofficial VRAM numbers as requirements. For environment and weights, use <a href=\"/blog/run-tencent-auk-locally\">the local guide</a>; for supported tasks see <a href=\"/blog/tencent-auk-speech-editing-guide\">the workflow guide</a>; and return to the <a href=\"/blog/tencent-auk-speech-model\">main AuK overview</a> for license and release context."),
    ],
    sources: aukSources,
    relatedPaths: ["/blog/tencent-auk-speech-model", "/blog/run-tencent-auk-locally", "/blog/tencent-auk-speech-editing-guide"],
  },
];
