import type { ArticleBlock, ArticleSection, BlogArticle } from "./blog-types.ts";

const service = "/services/web-design-for-local-businesses";
const repo = "https://github.com/Projectmonetspace/ProjectMonetspace/blob/bc2f0f514b98ecadf60b00da311a389577521b5b/";
const p = (html: string): ArticleBlock => ({ type: "paragraph", html });
const note = (html: string): ArticleBlock => ({ type: "note", html });
const list = (...items: string[]): ArticleBlock => ({ type: "list", items });
const section = (id: string, title: string, ...blocks: ArticleBlock[]): ArticleSection => ({ id, title, blocks });
const source = (label: string, url: string) => ({ label, url });

type GuideInput = {
  slug: string; title: string; metaTitle: string; description: string; query: string;
  intent: string; audience: string; purpose: string; contribution: string;
  category: "Web" | "SEO"; sections: ArticleSection[];
  sources: BlogArticle["sources"]; relatedPaths: string[];
};

function guide(input: GuideInput): BlogArticle {
  return {
    status: "published", articleType: "main", cluster: input.slug,
    slug: input.slug, title: input.title, h1: input.title, metaTitle: input.metaTitle,
    metaDescription: input.description, excerpt: input.description,
    targetQuery: input.query, targetSearchIntent: input.intent,
    category: input.category, author: "Project Monet",
    datePublished: "2026-10-06", dateModified: "2026-10-06",
    ogAlt: `Project Monet guide: ${input.title}`,
    editorial: {
      focus: "website-search-conversion", businessPurpose: input.purpose,
      audience: input.audience, originalContribution: input.contribution,
      evidenceUrls: input.sources.map(item => item.url), servicePath: service,
      cta: "Discuss a scoped website review using your actual pages and business requirements.",
    },
    sections: input.sections, sources: input.sources,
    relatedPaths: [...new Set([...input.relatedPaths, service])],
  };
}

export const websiteGuides20261006: BlogArticle[] = [
  guide({
    slug: "small-business-website-redesign-seo-checklist",
    title: "A Small-Business Website Redesign Checklist",
    metaTitle: "Website Redesign SEO Checklist | Project Monet",
    description: "Plan a website redesign with a URL decision sheet, equivalent redirects, real 404s and launch checks. See a documented Project Monet migration example.",
    query: "small business website redesign checklist",
    intent: "Plan a replacement website and verify the migration without promising unchanged rankings",
    audience: "Business owners replacing an existing website",
    purpose: "Help owners scope a redesign while preserving useful customer paths and search signals",
    contribution: "A reusable URL decision sheet and launch acceptance checklist tied to this site's verified cleanup",
    category: "SEO",
    sections: [
      section("before-design", "Start with what the existing website does",
        p("Before choosing a new layout, list the pages customers use and the decisions those pages support. A service page may receive few visits yet be the exact link a prospect needs before requesting a quote. A redesign should preserve useful information and routes, then improve the parts that make the decision harder."),
        p("Save a dated baseline: current URLs, page titles, Search Console page/query reports, consented organic landing data and known external links. Separate customer activity from staff tests where the evidence permits. Missing analytics rows are not proof that a URL has never been indexed or has no backlinks."),
        list("Name the main customer and the action they need to take.", "Record the content, domain and hosting owners.", "List pages with enquiries, useful search impressions or known links.", "Agree who approves new copy, media and the launch.")),
      section("url-decisions", "Give each old URL an explicit decision",
        p("Use one row per existing URL: old URL; customer purpose; observed evidence and date range; keep, improve, merge or remove; replacement URL if equivalent; implementation owner; verification result. This makes the migration reviewable before the old site disappears."),
        p("Keep a stable URL when its purpose remains useful. Improve the existing page when the question is unchanged. Merge genuinely overlapping content into its strongest owner and use a permanent redirect. When a page is removed and has no useful equivalent, return a genuine 404 or 410 instead of sending everyone to the homepage."),
        note("Project Monet's October 2026 cleanup recorded 367 blog decisions: 244 KEEP, 8 IMPROVE, 13 MERGE and 102 PURGE. The resulting 252 retained articles were verified on 6 October before this new guide batch. These are implementation counts, not evidence of increased rankings or enquiries.")),
      section("staging", "Review the replacement before switching traffic",
        p("Use a staging or preview deployment to check content and behaviour without treating it as the public website. Review the homepage and several different page types on a phone: service, project, contact and article. Test the actual contact handoff rather than just checking whether a button looks clickable."),
        list("Check one clear H1, accurate title/description and intended canonical on each page type.", "Check visible text, image descriptions, navigation and accessible form labels.", "Verify that temporary crawl blocks are appropriate on preview and will be removed from production.", "Test successful and failed form submission; confirm receipt without claiming a booked or qualified customer.", "Keep original media and a recoverable copy of the old content.")),
      section("launch", "Test responses as well as appearances",
        p("A branded error page can look correct while returning HTTP 200. Test the response status of removed URLs and the actual destination of merged URLs. Include old variants that people or search engines may still request, such as extension-bearing paths, when the old site used them."),
        p("On this site, stale article responses required a scoped Cloudflare Pages handler that returns no-store 404s before consulting assets. The verification checked 306 removed clean, .html and OG paths plus equivalent redirects. That is a documented solution to this site's release issue, not a universal reason to add a custom handler to every redesign."),
        list("Confirm that the domain serves the intended release.", "Request every old-to-new redirect and verify a useful final page.", "Check the sitemap contains the intended canonical set.", "Keep unknown URLs as genuine errors, not homepage copies.")),
      section("after-launch", "Monitor the move without promising fixed rankings",
        p("Google explains that significant site changes can cause temporary ranking fluctuations while it recrawls and reprocesses URLs. A technically correct migration does not guarantee unchanged visibility. Keep Search Console access, submit the appropriate sitemap and watch for unexpected crawl, canonical or server problems."),
        p("Compare meaningful periods and customer outcomes. A launch-day traffic change is not enough to diagnose success or failure. Investigate a broken service page or contact path immediately; give indexing and ranking changes enough context before attributing them to the new design.")),
      section("scope", "Bring the decision sheet into the redesign brief",
        p("The useful handover is a URL ledger, agreed replacement content, redirect ownership, a launch checklist and someone responsible for monitoring. It is easier to price a redesign when the provider can see which pages need preservation, substantial rewriting or a separate integration."),
        p('Use the <a href="/resources/write-small-business-website-brief">website brief guide</a> to capture those requirements. For a scoped review, <a href="/services/web-design-for-local-businesses">discuss your existing website with Project Monet</a>; the review should start from actual URLs and business decisions.')),
    ],
    sources: [source("Google: moving a site", "https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes"), source("Google: redirects", "https://developers.google.com/search/docs/crawling-indexing/301-redirects"), source("Project Monet: dated URL decision ledger", `${repo}docs/content-url-decisions-2026-10-05.csv`), source("Project Monet: verified production run", "https://github.com/Projectmonetspace/ProjectMonetspace/actions/runs/37432809581")],
    relatedPaths: ["/resources/write-small-business-website-brief", "/resources/website-maintenance", "/blog/cloudflare-pages-website-launch-handover"],
  }),
  guide({
    slug: "ga4-call-whatsapp-clicks-lead-measurement",
    title: "Measure Call and WhatsApp Clicks Without Inventing Leads",
    metaTitle: "GA4 Call & WhatsApp Click Tracking | Project Monet",
    description: "Separate contact clicks, successful form submissions and qualified leads. Use a consent-aware event map and test worksheet for your business website.",
    query: "track whatsapp clicks ga4",
    intent: "Implement an honest contact-event measurement plan and verify the event triggers",
    audience: "Owners and developers measuring website enquiries",
    purpose: "Help businesses distinguish website interactions from received and qualified enquiries",
    contribution: "An event/consent test worksheet grounded in this repository's call tracking and confirmed form-success logic",
    category: "Web",
    sections: [
      section("meaning", "Decide what each event proves",
        p("A visitor opening a phone or WhatsApp link has shown an intention to contact you. They may close the app, abandon the message or call outside your operating hours. Recording that interaction is useful; labelling it a completed conversation or qualified lead overstates what the website can observe."),
        p("Write the event meaning before configuring Analytics. Google recommends generate_lead for submitting a form or a request for information, and separate lead-funnel events for later qualification. The relevant event should fire when that step actually occurs, rather than because a related button was clicked."),
        list("Contact-link click: the link was activated.", "Successful form: the receiving service confirmed submission.", "Received enquiry: the team or connected system has the message.", "Qualified lead: someone checked the enquiry against agreed criteria.", "Customer: the actual commercial conversion is recorded.")),
      section("map", "Make an event map for your real links",
        p("For each contact action, record the page, link selector, destination type, event name, permitted parameters and trigger. A proposed WhatsApp event could be named click_to_whatsapp. This is a suggested naming choice, not an automatic GA4 event or a claim that this site already implements every WhatsApp variant."),
        p("This repository records click_to_call for tel: links. Its generic data-analytics-event hook supports explicitly named link interactions. If your site adds a WhatsApp link, wire the intended event to that actual element or an appropriate destination rule, and test it. Avoid attaching two handlers that count one action twice."),
        list("Use page_path and a controlled link_location label to compare placements.", "Keep phone numbers, email addresses and message text out of Analytics parameters.", "Define how keyboard activation and dynamically inserted links are handled.", "Check every contact component, not only the homepage button.")),
      section("consent", "Treat consent as part of the trigger",
        p("Project Monet's trackAnalyticsEvent helper checks whether pm_analytics_consent is granted before sending an event to gtag. Its form emits generate_lead only after both a successful HTTP response and success=true from the receiving service. This demonstrates the intended guard; it does not prove delivery to a specific business inbox or real-world lead quality."),
        p("Your implementation needs a clear consent state and a consistent way to apply it to every tracker. A click count gathered under one consent rule should not be compared casually with another period or tool that observes a different population."),
        note("The examples describe the source code reviewed for this guide. They are not a report of production conversion totals, completed WhatsApp conversations or qualified customers.")),
      section("test", "Use a small acceptance worksheet",
        p("Test with identifiable test sessions and record the page, action, consent state, expected event, observed event and result. Use GA4 DebugView or the relevant development diagnostics to inspect the event that arrived. Do not leave test identifiers or personal information in public event parameters."),
        list("Consent denied + contact click: no Analytics event under this site's policy.", "Consent granted + one call click: one call-interaction event.", "Consent granted + configured WhatsApp click: one event for that actual element.", "Form validation failure or provider error: no successful-submission event.", "Confirmed successful submission: one generate_lead event.", "One activation on a tagged contact link: no duplicate generic event."),
        p("Also check whether a rapid navigation loses an event and whether opening the destination still works. Tracking must support the contact journey. It should never delay or block a customer just to improve the dashboard.")),
      section("report", "Compare interactions with the team's records",
        p("Keep separate columns for contact clicks, confirmed submissions, received enquiries, qualified enquiries and customers. Where systems can be reconciled safely, use their actual records rather than assuming a fixed percentage of clicks becomes leads. If you cannot observe the later stage, leave it unknown."),
        p("Marking an event as a GA4 key event changes reporting treatment; it does not establish that a conversation happened. Explain what your chosen key event represents to anyone reading the report. Segment staff tests and spam where reliable evidence allows.")),
      section("scope", "Choose measurement that the business can maintain",
        p('The <a href="/resources/website-more-calls-whatsapp-enquiries">calls and WhatsApp enquiry guide</a> covers making the contact path clearer. This guide addresses the separate implementation question: what the resulting events can truthfully tell you.'),
        p('Bring the event map and test worksheet to a <a href="/services/web-design-for-local-businesses">website measurement review</a>. Agree responsibility for the website, Analytics and the team\'s follow-up records before calling the system complete.')),
    ],
    sources: [source("Google Analytics: recommended events", "https://support.google.com/analytics/answer/9267735?hl=en"), source("Project Monet: consent-aware event helper", `${repo}app/lib/analytics.ts`), source("Project Monet: link event handlers", `${repo}app/components/analytics-events.tsx`), source("Project Monet: confirmed form-success event", `${repo}app/components/demo-request-form.tsx`)],
    relatedPaths: ["/resources/website-more-calls-whatsapp-enquiries", "/resources/write-small-business-website-brief", "/blog/small-business-website-redesign-seo-checklist"],
  }),
  guide({
    slug: "business-website-not-indexed-google",
    title: "Why Is My Business Website Not Indexed by Google?",
    metaTitle: "Website Not Indexed by Google? | Project Monet",
    description: "Work through missing pages, crawl blocks, canonical choices and server responses. Use an indexing decision tree before requesting another Google crawl.",
    query: "website not indexed by google",
    intent: "Diagnose whether a business page is absent, inaccessible or an expected duplicate/retirement",
    audience: "Business owners investigating a missing website or page",
    purpose: "Help owners commission the right technical or content repair instead of repeated submission",
    contribution: "A decision tree that separates intended retirements, technical eligibility, canonical issues and content review",
    category: "SEO",
    sections: [
      section("confirm", "Separate missing from ranking lower",
        p("A page not appearing for your preferred phrase is not enough to show that Google has excluded it. It may be indexed but rank below the results you checked, or Google may show a different canonical URL. First write down the exact page URL and the search you used."),
        p("Use Search Console URL Inspection for the page and review its indexed state and chosen canonical. A site: search can provide a quick clue, but it should not replace the more specific diagnosis. Record the inspection date and whether the result describes Google's indexed copy or a live test."),
        list("Is the page missing, or is the expected query ranking weak?", "Which URL does Google consider canonical?", "Was the page created or materially changed recently?", "Should this URL be indexed at all?")),
      section("expected", "Check whether exclusion is intentional",
        p("A redirect, retired article, preview page or alternate URL may correctly be excluded. The goal is not to make every historical address appear in search. The useful goal is an accessible, indexable canonical page that answers the customer's question."),
        p("In Project Monet's documented cleanup, 102 article slugs intentionally became genuine 404s and 13 overlapping articles permanently redirected to equivalent owners. Those old pages should not be restored just to remove an exclusion count. The retained destination is the page to inspect."),
        note("The cleanup's release checks verified HTTP behaviour, canonicals and sitemap coverage. They do not prove that all retained pages are indexed or that a newly published page will be indexed.")),
      section("technical", "Inspect the actual response and access rules",
        p("For an intended public canonical page, check whether it loads successfully and presents the intended content. An error layout returning 200, an authentication wall or a broken redirect can mislead a visual check. Review the response alongside what a visitor and crawler receive."),
        list("Server response: intended successful page, not a hidden error or empty shell.", "Robots rules: crawling is allowed where appropriate.", "Indexing directive: no unintended noindex in HTML or headers.", "Canonical: points to the intended page rather than staging or an unrelated URL.", "Navigation and sitemap: provide routes to the canonical page.", "Host/CDN settings: do not accidentally block the relevant crawler."),
        p('If the issue began after crawler-policy changes, review the <a href="/blog/cloudflare-ai-crawler-googlebot-seo">crawler and Googlebot guide</a>. A policy for one crawler should not be assumed to describe every search or AI system.')),
      section("content", "When access works, investigate the page's purpose",
        p("A successful live test establishes technical accessibility at that moment, not guaranteed indexing. Google may select another canonical or choose not to index a page. Read the stated reason and compare the content with other pages answering the same customer question."),
        p("Ask whether this page has useful information of its own: a service's actual inclusions, a real location's hours and access, a documented project, or a substantive answer. If it only swaps a keyword or city name into the same template, improve or consolidate the relevant owner instead of multiplying submission requests.")),
      section("repair", "Make one diagnosis-led repair and retest",
        p("Keep a repair log with the exact URL, observed issue, evidence, change, live-test result and follow-up date. Remove an accidental block, repair the response or redirect, clarify the canonical, or improve the content according to the finding. Do not change unrelated settings just because the page is missing."),
        p("After a meaningful repair, use the appropriate Search Console workflow and keep the sitemap current. Crawling and processing take time; an indexing request is not a publication or ranking guarantee. Check manual actions and security reports if the evidence points to a wider problem.")),
      section("scope", "Bring the evidence to a technical review",
        p("A useful support request contains the affected URLs, inspection results, recent changes and intended page purpose. That lets a provider distinguish a hosting fault, an indexing directive, a canonical choice and a content problem before recommending work."),
        p('Use the <a href="/services/web-design-for-local-businesses">website review service</a> to scope the fix. For a site replacement, use the <a href="/blog/small-business-website-redesign-seo-checklist">redesign checklist</a> to prevent the same problem being carried into the next launch.')),
    ],
    sources: [source("Google: a page missing from Search", "https://support.google.com/webmasters/answer/7474347?hl=en"), source("Google: HTTP responses and crawling", "https://developers.google.com/search/docs/crawling-indexing/http-network-errors"), source("Project Monet: retained and retired URL ledger", `${repo}docs/content-url-decisions-2026-10-05.csv`)],
    relatedPaths: ["/blog/cloudflare-ai-crawler-googlebot-seo", "/blog/small-business-website-redesign-seo-checklist", "/resources/google-business-profile-vs-website"],
  }),
  guide({
    slug: "seo-aeo-geo-small-business-website",
    title: "SEO, AEO and GEO for a Small-Business Website",
    metaTitle: "SEO vs AEO vs GEO for Business | Project Monet",
    description: "Understand the search acronyms, shared website foundations and measurement limits. Plan useful buyer answers without promises of AI citations or rankings.",
    query: "seo vs aeo vs geo",
    intent: "Choose a grounded website search strategy rather than a vendor-specific AI visibility setup",
    audience: "Owners comparing website search and AI visibility services",
    purpose: "Help buyers distinguish useful search work from unsupported visibility promises",
    contribution: "A customer-question-to-page planning worksheet and a claims/measurement review for service proposals",
    category: "SEO",
    sections: [
      section("terms", "Translate the labels into customer questions",
        p("SEO usually describes work that helps a website be understood and found in search. AEO is commonly used for answer-oriented visibility, and GEO for visibility in generative answers. Providers use these labels differently. Ask what pages, technical changes and evidence the proposal actually includes."),
        p("A local business does not need three contradictory versions of its offer. A customer still needs to know what you do, where you operate, what it involves and why they should trust it. Search interfaces may present those answers differently, but the underlying business information must remain accurate.")),
      section("foundations", "Start with Google's stated requirements",
        p("Google's AI-features guidance applies the usual Search foundations to AI Overviews and AI Mode. A supporting page must be indexed and eligible to appear with a snippet. The documentation does not introduce an additional technical eligibility requirement just for those features."),
        list("Make important information available as readable text.", "Allow appropriate crawling and link useful pages from the site.", "Keep business information and visible structured data consistent.", "Give each page a clear purpose and credible original detail.", "Maintain a usable page and contact journey on mobile."),
        p("This is guidance for Google's features. It is not proof that another answer service uses identical retrieval, that any system will cite your page, or that a special file can guarantee visibility.")),
      section("worksheet", "Map buyer questions to existing pages",
        p("Create a worksheet with five columns: customer question; existing canonical page; missing answer or proof; source/content owner; useful next action. Start with questions the business hears repeatedly. A question such as whether you cover a particular area may belong on a service page rather than in a new glossary article."),
        list("What exactly is included? Add agreed scope and exclusions to the service owner.", "What will it cost? Link a truthful pricing explanation with its conditions.", "Can I see relevant work? Show real projects or clearly labelled concepts.", "What happens after I enquire? Explain the actual follow-up process.", "Why should I trust this claim? Add permission-based evidence, not an invented testimonial."),
        p("This worksheet is a planning tool, not a formula for winning citations. It helps keep the website useful even when the visitor arrives directly or a search interface changes.")),
      section("measure", "Measure visibility and enquiries separately",
        p("Google's documentation describes AI-feature traffic within Search Console's Web reporting. That does not turn every visit into evidence of a particular AI answer or into a qualified enquiry. Report only what the actual data can support."),
        p("For manually checked AI responses, save the question, system, date, relevant context and visible sources. Repeated observations can show changes in those checks; they do not establish universal visibility. Alongside those observations, track consented website activity and genuine enquiry outcomes without treating contact clicks as sales.")),
      section("proposal", "Review the deliverables before buying the acronym",
        p("A useful proposal names the existing pages to improve, evidence to add, technical defects to fix and the method for checking the result. It should distinguish the provider's work from outcomes controlled by search or answer systems."),
        list("Ask which customer decision each new URL serves.", "Ask where original evidence will come from.", "Reject invented ranking, citation or revenue results.", "Separate tool observations from business enquiries.", "Check who owns the accounts and maintains the information."),
        p('The <a href="/blog/mentionos-autonomous-aeo-agent">MentionOS evaluation guide</a> and <a href="/blog/rankly-seo-aeo-geo-website-audit">Rankly audit guide</a> address tool-specific workflows. They should support the page plan, not replace it.')),
      section("scope", "Agree a useful website scope",
        p("For a small business, clear service information, honest proof, accessible pages and a reliable contact route can be a sensible starting point. Add more specialised work when a specific need and available evidence justify it."),
        p('Bring the question-to-page worksheet to <a href="/services/web-design-for-local-businesses">Project Monet\'s website planning review</a>. Agree deliverables and measurement limits before turning an acronym into a promise.')),
    ],
    sources: [source("Google: AI features and your website", "https://developers.google.com/search/docs/appearance/ai-features"), source("Google: Search spam policies", "https://developers.google.com/search/docs/essentials/spam-policies"), source("Project Monet: current website strategy and evidence limits", `${repo}docs/content-strategy-2026-10-05.md`)],
    relatedPaths: ["/blog/mentionos-autonomous-aeo-agent", "/blog/rankly-seo-aeo-geo-website-audit", "/blog/ga4-call-whatsapp-clicks-lead-measurement", "/resources/write-small-business-website-brief"],
  }),
  guide({
    slug: "service-pages-vs-location-pages-local-business",
    title: "Service Pages or Location Pages: What Does Your Site Need?",
    metaTitle: "Service Pages vs Location Pages | Project Monet",
    description: "Choose pages for genuinely different services and places. Use a page-purpose worksheet to avoid thin city templates and make local enquiries clearer.",
    query: "service pages vs location pages",
    intent: "Decide which service and location purposes merit separate canonical pages",
    audience: "Local businesses planning a multi-page website",
    purpose: "Help owners scope distinct service/location pages without misleading local coverage",
    contribution: "A service-area decision worksheet with a labelled hypothetical page hierarchy and maintenance ownership",
    category: "SEO",
    sections: [
      section("difference", "A service page explains the work; a location page explains the place",
        p("A service page helps someone understand a specific offer: who it is for, what is included, exclusions, relevant proof and how to request it. A location page helps someone use or assess a real place or service area: access, operating details, local availability and the appropriate contact route."),
        p("The labels alone do not justify separate URLs. A business with one office and a simple offer may answer both needs on a focused site. Another may need several substantial service pages and distinct branch pages. Begin with what differs for the customer.")),
      section("worksheet", "Give every proposed page a job",
        p("Use a row for each proposed page: customer question; service or place; facts that differ; evidence owner; contact destination; existing owner; review frequency. If two rows answer the same question using the same facts, combine them until there is a real reason to separate them."),
        list("Service difference: scope, eligibility, process or proof changes materially.", "Location difference: actual address, hours, access or available team changes.", "Service-area difference: real operating constraints or local work add useful detail.", "Maintenance capacity: someone can keep each detail current.", "Visitor route: navigation and internal links explain how the pages relate."),
        p("A useful check is whether you would send this exact page to a customer asking a different question. If the only difference is the city name in the title, the proposed page needs more thought.")),
      section("example", "A labelled example architecture",
        note("The following is a hypothetical planning example. It does not describe Project Monet's offices, customers or a completed client's results."),
        p("Imagine a home-services business offering repair and scheduled maintenance from one real office. The repair page could describe urgent assessment and exclusions; maintenance could describe an agreed recurring visit. The office/contact page could give access and operating hours. A shared service-area explanation may be enough for neighbouring districts."),
        p("If the business later opens a genuinely different branch, a location page can describe that branch's actual team, hours, access and available services. Do not create the branch page in advance just to imply local presence. Each additional page needs content and a person responsible for it.")),
      section("risk", "Avoid doorway-style expansion",
        p("Google's doorway policy describes pages created for similar queries that funnel people through less useful intermediate pages. This is a useful reason to avoid near-identical city pages. It is not a rule that every location page is prohibited or that a particular word count makes a page legitimate."),
        p("Use genuine local facts where relevant and permitted: actual work context, service availability, directions or operating details. Do not invent addresses, local teams, reviews or completed projects. Link pages into a understandable hierarchy rather than making visitors navigate a long list of interchangeable place names.")),
      section("existing", "Preserve the existing decision owners",
        p('The <a href="/resources/one-page-vs-multi-page-website">one-page versus multi-page guide</a> answers the broader scope decision. The <a href="/industries/home-services">home-services page</a> describes a commercial website offer. A service/location plan should link to those owners rather than rewriting their entire purpose.'),
        p("For an established site, audit existing URLs before adding more. Keep useful pages, improve missing details and merge overlapping owners with equivalent redirects where appropriate. A location strategy should not create competing versions of the same service explanation.")),
      section("scope", "Make content responsibility part of the quote",
        p("Ask the provider to quote against the agreed purpose sheet: pages, actual content, approvals, contact routing, maintenance and necessary integrations. A large promised page count does not compensate for missing business information."),
        p('Use <a href="/services/web-design-for-local-businesses">Project Monet\'s website scope review</a> to choose a structure the business can support. The result should make services and places easier to understand, with no fictional local footprint.')),
    ],
    sources: [source("Google: doorway and other spam policies", "https://developers.google.com/search/docs/essentials/spam-policies"), source("Project Monet: page-count and scope guide", "https://www.projectmonet.space/resources/one-page-vs-multi-page-website"), source("Project Monet: home-services website requirements", "https://www.projectmonet.space/industries/home-services")],
    relatedPaths: ["/resources/one-page-vs-multi-page-website", "/industries/home-services", "/resources/local-business-website-sections", "/blog/small-business-website-redesign-seo-checklist"],
  }),
  guide({
    slug: "interior-design-portfolio-project-page-template",
    title: "An Interior-Design Portfolio Project Page That Explains the Work",
    metaTitle: "Interior Portfolio Project Page Guide | Project Monet",
    description: "Turn a gallery into useful project context with a brief, constraints, decisions and credits. Use a copy-and-fill outline without inventing client proof.",
    query: "interior design portfolio project page",
    intent: "Write a useful individual interior project page, distinct from buying a website or viewing a concept",
    audience: "Interior studios preparing permission-based project content",
    purpose: "Help studios explain relevant work so prospective customers can assess fit before an enquiry",
    contribution: "An original copy-and-fill project outline and a clearly labelled mapping to the existing interior concept",
    category: "Web",
    sections: [
      section("context", "Give the photographs a decision to support",
        p("A portfolio gallery can show taste while leaving a customer unsure what the studio actually did. An individual project page should help someone understand the brief, constraints, studio's role and decisions behind the images. That gives the visitor a better basis for deciding whether to enquire."),
        p("Keep the context proportional to the work. A completed home, a single-room consultation and a speculative concept need different labels. A customer should be able to distinguish them without reading a legal footnote or inferring the truth from a caption.")),
      section("outline", "Use this copy-and-fill project outline",
        list("Project status: [completed / in progress / concept] and what that status means.", "Brief: [who the space serves and the decision the client needed].", "Scope and role: [what the studio designed, specified or supervised].", "Constraints: [relevant space, budget band, timeline or practical restrictions, if permitted].", "Decisions: [two or three choices and why they suited the brief].", "Image context: [room or detail, purpose and relevant material].", "Credits and permissions: [photographer, collaborators and approved disclosure].", "Next step: [the relevant consultation or enquiry path]."),
        p("Replace the brackets with verifiable facts. Leave out information the client has not approved, including exact addresses and private budgets. If a field cannot be supported, remove it or explain the limit; do not fill it with a plausible story."),
        p("Keep the project name useful and descriptive without exposing a private client. The page title, headings and short introduction should tell a visitor the type of work and its status before they start scrolling through photographs.")),
      section("concept", "Apply the outline honestly to a concept",
        note('The <a href="/work/interior-design-website-concept">Project Monet interior-design website concept</a> is a speculative interface. It is not a commissioned interior project, paid-client testimonial or evidence of enquiry growth.'),
        p("As an annotated planning example, its visual direction can help a studio decide where a portfolio entry belongs and how a customer moves from work to an enquiry. The project outline above shows the production content that would need to accompany a real studio's images."),
        p("For a concept entry, write the hypothetical brief explicitly and describe design decisions as proposed choices. Do not claim a client budget, finished installation, completion date or customer reaction. Concept work can demonstrate reasoning without borrowing the credibility of a project that did not happen.")),
      section("images", "Make each image useful and permitted",
        p("Choose images that show the relevant decisions rather than repeating nearly identical angles. Add concise captions where the photograph needs context. A material close-up can explain a choice; a room overview can explain layout. The sequence should make sense on a phone as well as a wide screen."),
        p("Google's image guidance supports discoverable HTML images, useful surrounding information and responsive delivery. Write accurate image descriptions rather than stuffing locations and services into every alt attribute. Retain the necessary usage permissions and credit obligations alongside the content."),
        list("Check image rights and client permission before publication.", "Avoid exposing identifying details unintentionally.", "Preserve the original files and review any delivery changes visually.", "Use captions to explain context that the image alone cannot show.")),
      section("enquiry", "Connect the project to the right conversation",
        p("After the project explanation, give a relevant next step: discuss a similar room, enquire about a complete-home scope or ask about consultation availability. A general contact form may be sufficient, but it should explain what information helps the studio respond."),
        p("Ask only what is useful for the next step. Project type, location at an appropriate level, desired scope and a contact route may be enough initially. Do not ask a visitor to submit private drawings or sensitive property details simply to see whether the studio is available.")),
      section("scope", "Build the portfolio around evidence you can supply",
        p("Prepare one complete project entry before commissioning a large archive. It reveals missing permissions, image context, copy and approval responsibilities early. The website provider can then quote the layout and editing workflow against real content instead of assumptions."),
        p('Bring the outline, approved images and intended enquiry path to a <a href="/services/web-design-for-local-businesses">portfolio website review</a>. Project Monet can help scope the website; the studio remains responsible for accurate project facts and permitted proof.')),
    ],
    sources: [source("Project Monet: labelled interior website concept", "https://www.projectmonet.space/work/interior-design-website-concept"), source("Project Monet: concept content and disclosure", `${repo}app/lib/phase-two-content.ts`), source("Google: image search guidance", "https://developers.google.com/search/docs/appearance/google-images")],
    relatedPaths: ["/work/interior-design-website-concept", "/resources/write-small-business-website-brief", "/blog/mobile-website-speed-images-video-checklist"],
  }),
  guide({
    slug: "restaurant-website-menu-hours-local-search-checklist",
    title: "A Restaurant Website Checklist for Menus, Hours and Visits",
    metaTitle: "Restaurant Website SEO Checklist | Project Monet",
    description: "Check the menu, opening hours, location and reservation handoff on a phone. Use a maintenance worksheet and an honestly labelled restaurant concept.",
    query: "restaurant website seo checklist",
    intent: "Audit practical restaurant information and visit/booking paths, rather than purchase a design service",
    audience: "Restaurant owners maintaining public menu and visit information",
    purpose: "Help restaurants prevent avoidable friction between discovery and a real visit or booking request",
    contribution: "A mobile visit-path audit and information-maintenance worksheet mapped to the restaurant concept",
    category: "SEO",
    sections: [
      section("visit", "Start with a hungry visitor's immediate questions",
        p("A restaurant visitor may want to check today's hours, compare a dish, find the address or understand how to book. They may be standing outside, travelling or using a slow connection. Put the information that changes the visit decision within easy reach."),
        p("A beautiful opening screen should lead somewhere useful. If the visitor has to search through a large image for a menu or guess whether a reservation button confirms a table, the website has created uncertainty at the moment it should clarify it."),
        list("Can I see the relevant menu and prices?", "Are these today's opening hours?", "Which location am I looking at?", "Do I need to reserve, call or use another platform?", "What does the next action actually confirm?")),
      section("menu", "Keep the menu readable and maintainable",
        p("Give the essential menu a readable web presentation. A downloadable PDF can still be useful, but it should not be the only way to inspect food on a phone. Review text size, categories, prices and any conditions that affect ordering."),
        p("Use the restaurant's approved current information. If availability or prices vary, explain the actual rule instead of showing an invented universal menu. Dietary or allergen statements need the restaurant's operational review; the website provider should not infer them from dish names or photographs."),
        list("Record who approves menu changes and who makes the website edit.", "Check the menu link from the homepage and location/contact path.", "Keep useful text visible rather than embedded only in an oversized image.", "Check that a downloaded menu and the web version do not contradict each other.")),
      section("hours", "Give hours and location an owner",
        p("Treat opening times, contact details and addresses as operational content. A correct design with outdated holiday hours can still send customers to a closed venue. Use a maintenance sheet with the field, source of truth, approver, last review and next review trigger."),
        p("For several locations, show which details belong to which venue and route the contact or booking action correctly. Do not create a location page for a place the restaurant does not operate. Keep the public website and business listings consistent when the actual information changes."),
        p("Google's LocalBusiness documentation describes business details such as hours and provides a Restaurant example with a menu URL. Structured data should describe the real visible business information; it is not a substitute for a usable menu or a promise of a rich result.")),
      section("handoff", "Test what the reservation or order button does",
        p("Open the booking or ordering destination on a phone and complete an appropriate authorised test. Check the right venue, intended offer, confirmation wording and error path. If the website merely opens another platform, explain that handoff rather than implying that the website itself has confirmed availability."),
        list("Check call and directions links for the correct destination.", "Explain whether a form is a request or a confirmed reservation.", "Show relevant operating limits before someone submits.", "Test broken links and unavailable external systems.", "Keep click events separate from confirmed bookings or received enquiries.")),
      section("concept", "Use the concept as a layout example, not a restaurant result",
        note('The <a href="/work/restaurant-website-concept">Project Monet restaurant website concept</a> demonstrates a speculative interface. It does not represent a paying restaurant client, live reservation inventory or measured search results.'),
        p("For an original review, walk through the concept's menu, hours/location and contact decisions, then list the real business content and systems a production version would require. Replace illustrative details with approved operating information before putting a restaurant's name on the site."),
        p("This checklist addresses upkeep and visit decisions. The concept shows a visual direction, while a commercial service page explains what the provider can build. Keeping those purposes distinct makes each page more useful.")),
      section("scope", "Agree the editing and integration scope",
        p("A brochure menu, a maintained restaurant site and a complete ordering system are different projects. Decide who changes dishes and hours, which platform controls reservations and what support is needed when that system fails."),
        p('Bring the menu, location details and current booking path to a <a href="/services/web-design-for-local-businesses">restaurant website review</a>. Quote the actual operational requirements and content responsibility alongside the visual design.')),
    ],
    sources: [source("Google: LocalBusiness and restaurant structured data", "https://developers.google.com/search/docs/appearance/structured-data/local-business"), source("Project Monet: labelled restaurant concept", "https://www.projectmonet.space/work/restaurant-website-concept"), source("Project Monet: calls and enquiry decisions", "https://www.projectmonet.space/resources/website-more-calls-whatsapp-enquiries")],
    relatedPaths: ["/work/restaurant-website-concept", "/resources/google-business-profile-vs-website", "/blog/ga4-call-whatsapp-clicks-lead-measurement"],
  }),
  guide({
    slug: "mobile-website-speed-images-video-checklist",
    title: "Improve Mobile Website Speed Without Losing Useful Media",
    metaTitle: "Mobile Website Speed & Media Checklist | Project Monet",
    description: "Diagnose mobile loading, separate lab and field evidence, and review images and video without claiming unmeasured gains or deleting useful business proof.",
    query: "improve mobile website speed",
    intent: "Choose evidence-led mobile performance work and review media quality with a reproducible test worksheet",
    audience: "Business owners and developers reviewing a slow visual website",
    purpose: "Help owners scope mobile performance changes while preserving useful presentation and proof",
    contribution: "A repeatable page/device measurement worksheet and original-media review based on this site's preservation contract",
    category: "Web",
    sections: [
      section("baseline", "Measure the page that feels slow",
        p("Start with the actual page and action: waiting for the opening image, scrolling a portfolio, opening the menu or using a form. A single headline score does not explain which part of that journey is slow. Save the URL, release, device profile, network setting, tool and date before changing anything."),
        p("Separate controlled lab results from field data collected from real visits. Google's web.dev LCP guidance explains why lab tools can help diagnose loading but do not necessarily represent every user's experience. When field data is unavailable, report that limit rather than substituting a lab score as proof of real-user improvement."),
        note("This guide provides a measurement method. It does not report a new Project Monet speed score, before/after improvement or field-performance result. Preserving original assets is an implementation fact, not proof of faster loading.")),
      section("worksheet", "Use the same conditions for the comparison",
        list("Page and release: [exact URL and deployed commit/version].", "Scenario: [cold load / repeat visit / scrolling / contact action].", "Lab environment: [tool, viewport, network and CPU settings].", "Runs: [repeat results, including variability and failures].", "Field evidence: [URL/origin, device segment, period or unavailable].", "Observed issue: [resource, render delay, layout movement or interaction].", "Change and visual review: [what changed and what remained readable/useful]."),
        p("Change a focused cause, then repeat the same scenario. Keep the individual results and explain variation. If the deployed release, test environment or page content changed in several ways, a clean before/after attribution is harder; disclose that instead of selecting only the best run."),
        p("Also test the customer's action. A faster-looking first screen is not a successful repair if the menu, gallery navigation or form has stopped working.")),
      section("images", "Deliver suitable images and keep the originals",
        p("Review which image is actually visible first, its delivered size and its place in the layout. Responsive delivery can let the browser select an appropriate version while keeping a fallback image. Explicit dimensions help reserve space. Review text, details and framing visually before accepting a new derivative."),
        p("Browser-level lazy loading can defer offscreen images, but Google's guidance warns against lazy-loading likely first-viewport or LCP images. Do not apply one blanket setting to every photo. The opening image and a distant portfolio image can have different loading needs."),
        p("Keep the original approved media separately. Project Monet's export checks compare the original public assets byte-for-byte; the publication batch does not recompress the reels. A future delivery change should be separately scoped and tested rather than quietly overwriting the originals.")),
      section("video", "Ask what the video contributes to the visit",
        p("A reel can show a design or service more clearly than static copy. It can also create an unnecessary download if every visitor receives several videos immediately. Review where the video appears, what its first frame communicates and whether the user has enough control to browse comfortably."),
        list("Keep key business information readable without relying on the video.", "Check media requests during the chosen test scenario.", "Review loading priority alongside the actual opening content.", "Avoid starting every offscreen media item solely because it exists.", "Test playback, controls and layout on the intended devices."),
        p("These are review questions, not a claim that a particular encoding or autoplay policy is always best. Choose the implementation against the business purpose, accessibility needs and measured behaviour.")),
      section("other-causes", "Look beyond the image file",
        p("Loading can be delayed by server response, redirects, render-blocking resources or client-side work. The LCP diagnostic process examines the loading sequence rather than assuming a single image edit will fix everything. Identify the bottleneck before changing the visible design."),
        p("Keep third-party scripts and animations accountable to a purpose. Remove or defer unnecessary work only after checking the integrations that depend on it. Analytics, consent and form success behaviour should remain correct after the performance change.")),
      section("scope", "Ask for a measured repair and an honest report",
        p("A useful performance scope names the affected pages, test conditions, planned change, visual acceptance and functional checks. It should distinguish a verified lab result, available field evidence and any outcomes that are still unknown."),
        p('Use a <a href="/services/web-design-for-local-businesses">mobile website review</a> to agree that scope. The <a href="/resources/website-maintenance">maintenance guide</a> explains broader upkeep; performance work should have its own evidence and acceptance criteria.')),
    ],
    sources: [source("web.dev: diagnose and optimise LCP", "https://web.dev/articles/optimize-lcp"), source("web.dev: browser-level image lazy loading", "https://web.dev/articles/browser-level-image-lazy-loading"), source("Google: responsive and discoverable images", "https://developers.google.com/search/docs/appearance/google-images"), source("Project Monet: original-media export verification", `${repo}scripts/verify-export.mjs`)],
    relatedPaths: ["/resources/website-maintenance", "/blog/interior-design-portfolio-project-page-template", "/blog/small-business-website-redesign-seo-checklist"],
  }),
  guide({
    slug: "small-store-ecommerce-product-page-checklist",
    title: "An Ecommerce Product Page Checklist for a Small Store",
    metaTitle: "Ecommerce Product Page Checklist | Project Monet",
    description: "Plan product details, variants, shipping, returns and checkout expectations. Use a copy-and-fill worksheet and a clearly labelled Shop Co design concept.",
    query: "ecommerce product page checklist",
    intent: "Prepare truthful product-page content and purchase acceptance checks, distinct from a storefront concept or service offer",
    audience: "Small stores preparing a real catalogue and ecommerce build",
    purpose: "Help store owners scope product information and operational handoffs before commissioning checkout",
    contribution: "A product-content worksheet and purchase-path acceptance checklist with a labelled concept/production distinction",
    category: "Web",
    sections: [
      section("decision", "Help a customer understand what they are buying",
        p("A product page should let someone assess the actual item, the selected option, total purchase conditions and the next step. A compelling product image is useful, but it cannot answer questions about size, delivery or what happens if the item is unsuitable."),
        p("Start with the catalogue and operating decisions. A provider cannot build truthful availability, shipping or return information from a visual concept alone. Assign a source and approver for product facts before those facts become public.")),
      section("worksheet", "Prepare one complete product record",
        list("Identity: [product name, identifier and actual seller/manufacturer relationship].", "Description: [what it is, intended use, materials and relevant dimensions].", "Options: [sizes/variants, differences and accurate images].", "Commercial information: [actual price, tax/display conditions and availability].", "Delivery: [where you ship, expected handling/transit and costs or calculation].", "Returns: [accessible policy, eligibility, method and costs].", "Media and proof: [rights, credits and genuine permitted reviews].", "Owner: [who updates each field and what triggers a review]."),
        p("Use the worksheet to expose gaps. Do not fill missing policies with generic promises such as free returns or guaranteed delivery. Keep manufacturer-supplied specifications identifiable and write original store information where your own context matters."),
        p("For variants, ensure the selected option and its availability match the content shown. A customer should not have to discover a different size, price or delivery condition after committing to checkout.")),
      section("concept", "Distinguish the storefront concept from a production store",
        note('The <a href="/work/shop-co-ecommerce-concept">Shop Co ecommerce concept</a> demonstrates a speculative retail interface. It is not a live merchant catalogue, functioning checkout or record of sales and conversion results.'),
        p("Its product previews and category routes can help discuss visual browsing. The worksheet above adds the production content a real store would need. Product data, inventory, payment provider, order communication, shipping and return workflows still need selection and testing."),
        p("That distinction gives the concept a useful role: evaluate the presentation before paying for the complete build, then quote the real operation. It should never make a buyer assume that a decorative purchase button already processes orders.")),
      section("policies", "Make purchase conditions easy to find",
        p("Place relevant delivery and return information where a customer can find it before checkout. Google Merchant Center's onboarding guidance emphasises clear operational details and accessible policies. A checklist can prepare information; it cannot guarantee account approval or listing eligibility."),
        p("Use the store's actual policy and applicable operating requirements. Explain any conditions that materially change the purchase. Keep website, checkout and product-feed information consistent when those systems are in use. The store owner must confirm what they can actually fulfil.")),
      section("acceptance", "Test the entire purchase path",
        list("Open the product page on a phone and select a valid option.", "Check the cart reflects the chosen item and quantity.", "Confirm price and relevant shipping information remain consistent.", "Use an authorised payment test and check success, failure and cancellation.", "Verify order communication and the appropriate internal record.", "Check that unavailable or invalid options do not silently proceed.", "Record the test environment and distinguish test orders from real sales."),
        p("Google's Product documentation distinguishes product snippets from merchant listings and describes relevant structured information. Markup must correspond to the real page and use case. Do not invent review ratings or claim a rich result merely because JSON-LD was added."),
        p("A front-end click is not a completed purchase. Analytics should follow the actual state transition and the business's consent policy. Keep test events and transactions identifiable in the verification process.")),
      section("scope", "Quote the store operation as well as the screen",
        p("A catalogue with enquiries, a hosted checkout and a custom ecommerce operation have different content, integration and support needs. Decide which model the business can operate before the design implies more capability than the scope includes."),
        p('Bring one complete product worksheet and your existing systems to a <a href="/services/web-design-for-local-businesses">store website scope review</a>. The <a href="/industries/ecommerce">ecommerce service page</a> explains the broader offer; this checklist helps make the required content and acceptance concrete.')),
    ],
    sources: [source("Google Merchant Center: website onboarding checklist", "https://support.google.com/merchants/checklist/16993969?hl=en"), source("Google: Product structured data", "https://developers.google.com/search/docs/appearance/structured-data/product"), source("Project Monet: labelled Shop Co concept", "https://www.projectmonet.space/work/shop-co-ecommerce-concept")],
    relatedPaths: ["/work/shop-co-ecommerce-concept", "/industries/ecommerce", "/resources/write-small-business-website-brief", "/blog/ga4-call-whatsapp-clicks-lead-measurement"],
  }),
  guide({
    slug: "cloudflare-pages-website-launch-handover",
    title: "What Happens During a Cloudflare Pages Website Launch?",
    metaTitle: "Cloudflare Pages Launch & Handover | Project Monet",
    description: "Understand the preview, release, domain, redirects, 404 checks and account handover. See a documented launch example without confusing deployment with indexing.",
    query: "cloudflare pages website launch",
    intent: "Understand buyer-facing launch acceptance and ownership, rather than a generic developer deployment tutorial",
    audience: "Owners reviewing a Cloudflare Pages launch or website handover",
    purpose: "Help buyers distinguish a completed deployment from a verified, maintainable website release",
    contribution: "A buyer-readable release acceptance and ownership checklist grounded in the site's verified Pages release",
    category: "Web",
    sections: [
      section("release", "A deployment is one step in the launch",
        p("A successful upload means the platform accepted an artefact. It does not establish that the customer's domain serves the intended version, old links work, forms submit or the owner has the necessary access. Agree what acceptance means before treating a deployment badge as completion."),
        p("For a small business, the acceptance list should cover the public pages, contact journey, search-facing URLs and ownership. The implementation can be technical, but the owner should receive a plain explanation of what was checked and who handles the next change.")),
      section("preview", "Use a preview for review and identify the release",
        p("A preview lets the business review content and behaviour before production changes. It should be clear which URL is a preview and which is the public website. Availability and creation of preview URLs depend on the project's deployment workflow; a Git-integrated example is not a promise that every upload creates the same review path."),
        p("Record the source commit or equivalent version, build result, intended production project and deployment identifier. Project Monet's public deployment marker and production check compare the exact deployed commit. That reduces the risk of reviewing one build and certifying another."),
        list("Approve the actual pages and media in the agreed review environment.", "Test relevant forms and integrations with authorised test data.", "Keep production canonicals and preview indexing controls appropriate.", "Record the exact version selected for launch.")),
      section("routing", "Check redirects and error responses on the real domain",
        p("Review the old URL map before launch. Equivalent permanent redirects should land on useful replacements; removed content without an equivalent should return a genuine error. Cloudflare Pages documentation describes extensionless route behaviour, custom 404 pages and SPA fallback when no top-level 404 exists."),
        p("Pages Functions and static redirects also need an intentional relationship. Cloudflare documents that _redirects rules do not apply to requests served by Functions. This site's routing excludes its merge redirects from the handler and handles retired blog routes before asset lookup. That is a specific design choice, not a checklist item to copy blindly."),
        p("Ask for response-level verification. A page that visually says not found but returns 200 has different behaviour from a true 404. Test the domain the customer will actually use, including relevant legacy variants.")),
      section("example", "What this site's release evidence shows",
        p("On 6 October 2026, Project Monet's strict production run verified the prior cleanup commit bc2f0f514b98ecadf60b00da311a389577521b5b. It checked 252 retained blog pages and their 1200×630 OG PNGs, core canonicals, 302 total sitemap URLs, merge redirects and the removed URL responses. This guide batch adds new pages after that dated checkpoint."),
        p("The earlier cleanup had 102 purged article slugs and 13 equivalent merge mappings. The test checked 306 removed clean, .html and OG paths, and both clean/.html merge redirects. Those counts document a release scope; they are not ranking, conversion or uptime guarantees."),
        note("Successful production checks establish the tested release behaviour. They do not prove Google indexing, search visibility gains or a customer's commercial result.")),
      section("ownership", "Make the handover usable",
        list("Domain/DNS: who controls the account and renewals?", "Source: which repository holds the website and who can access it?", "Hosting: which Pages project serves production and who can administer it?", "Integrations: who owns Analytics, Search Console and the form/booking service?", "Content: who changes hours, prices, project pages and policies?", "Support: what is included, how are incidents reported and who approves changes?", "Recovery: where are the source, deployment history and agreed rollback instructions?"),
        p("Transfer or grant the agreed account access securely; a screenshot of the dashboard is not ownership. Document third-party subscriptions and responsibilities accurately without putting secrets in the public website or an ordinary handover document."),
        p("Avoid changing DNS or deleting fallback hosting simply to make a normal content release look complete. Hosting changes and rollback retirement should follow the separately agreed migration and ownership plan.")),
      section("scope", "Agree launch evidence before paying for completion",
        p("A good launch report names the release, tested URLs, failures resolved, remaining limits and responsible owners. It should be short enough to use and detailed enough to investigate a future issue. Indexing and ongoing performance monitoring belong to their own evidence, not a deployment badge."),
        p('Read <a href="/website-ownership">website ownership</a> and <a href="/resources/website-maintenance">maintenance scope</a>, then <a href="/services/web-design-for-local-businesses">discuss the launch and handover requirements</a>. Project Monet should scope those responsibilities alongside the build.')),
    ],
    sources: [source("Cloudflare Pages: serving routes, errors and caching", "https://developers.cloudflare.com/pages/configuration/serving-pages/"), source("Cloudflare Pages: redirects and Functions", "https://developers.cloudflare.com/pages/configuration/redirects/"), source("Cloudflare Pages: preview deployments", "https://developers.cloudflare.com/pages/configuration/preview-deployments/"), source("Project Monet: dated successful production verification", "https://github.com/Projectmonetspace/ProjectMonetspace/actions/runs/37432809581"), source("Project Monet: production acceptance implementation", `${repo}tests/production-smoke.mjs`)],
    relatedPaths: ["/website-ownership", "/how-it-works", "/resources/website-maintenance", "/blog/small-business-website-redesign-seo-checklist", "/blog/business-website-not-indexed-google"],
  }),
];
