import type { BlogArticle } from "./blog-types.ts";

export const qwen38OmniFlashArticles: BlogArticle[] = [
  {
    status: "published", articleType: "main", cluster: "Qwen3.8-Omni-Flash",
    targetSearchIntent: "Broad overview of Qwen3.8-Omni-Flash capabilities, API access, limits, availability and practical use", targetQuery: "Qwen3.8 Omni Flash",
    slug: "qwen3-8-omni-flash", title: "Qwen3.8 Omni Flash: API, 1M Context, Audio & Video Guide", metaTitle: "Qwen3.8 Omni Flash: API, 1M Context, Audio & Video", metaDescription: "Qwen3.8-Omni-Flash explained: 1M context, text/image/audio/video input, tool calling, web search, reasoning, API access, regions and current limits.", h1: "Qwen3.8 Omni Flash: API, Multimodal Features, Context & Availability", excerpt: "Alibaba Cloud Model Studio's Qwen3.8-Omni-Flash accepts text, images, audio and video, returns text, and supports a 1M-token context window, tools and web search.", category: "AI", author: "Mayank", datePublished: "2026-09-21", dateModified: "2026-09-21", ogAlt: "Qwen3.8 Omni Flash multimodal API and 1M context overview",
    sections: [
      { id: "overview", title: "What Qwen3.8-Omni-Flash supports", blocks: [{ type: "paragraph", html: "Qwen3.8-Omni-Flash is a hosted Alibaba Cloud Model Studio model for understanding text, images, audio and video and returning text. Alibaba documents custom function calling, adjustable reasoning effort with thinking enabled by default, built-in web search through Responses, automatic implicit context caching and Responses Session caching." }, { type: "paragraph", html: "Audio input supports 113 languages and dialects. Chat Completions also supports multichannel or spatial audio through the documented multichannel option." }] },
      { id: "limits", title: "Context window and output limits", blocks: [{ type: "paragraph", html: "Alibaba documents a 1,000,000-token context window, with maximum input of 991,808 tokens in non-thinking mode and 983,616 tokens in thinking mode. Maximum output is 131,072 tokens. These are service ceilings, not recommended request sizes." }] },
      { id: "api", title: "API access and regions", blocks: [{ type: "paragraph", html: "The model ID is qwen3.8-omni-flash. Alibaba documents both Chat Completions and Responses. Supported regions currently include Beijing, Singapore, Hong Kong, Tokyo, Frankfurt and Virginia; use an API key from the selected region." }, { type: "paragraph", html: "For agent-style applications, multimodal input can be combined with custom function calling and Responses web search. Your application remains responsible for authentication, validation and side effects." }] },
      { id: "rate-limits", title: "Rate limits", blocks: [{ type: "paragraph", html: "Alibaba's current Qwen-Omni rate-limit table lists 30,000 requests per minute for Qwen3.8-Omni-Flash. Hong Kong, Tokyo, Frankfurt and Virginia list 2,000,000 tokens per minute, while Singapore and Beijing currently show dynamic token limits. Limits can change and should be checked for the deployment region." }] },
      { id: "media-tokens", title: "Media tokenization and caching", blocks: [{ type: "paragraph", html: "Alibaba documents audio input at seven tokens per second for Qwen3.8-Omni-Flash. Its Qwen-Omni documentation also describes image tokenization and caching behavior. Token accounting matters when combining long media with text inside the 1M context window." }] },
      { id: "availability", title: "Pricing and open-weight status", blocks: [{ type: "paragraph", html: "The model page points to Alibaba's Model Studio pricing information rather than embedding one stable cross-region price, so this guide does not hard-code a price." }, { type: "note", html: "This publication verified hosted Model Studio access. It did not verify an official open-weight release or official model card for Qwen3.8-Omni-Flash, so it does not describe the model as locally runnable." }] },
      { id: "faq", title: "FAQ", blocks: [{ type: "subheading", text: "Does it generate audio or video?" }, { type: "paragraph", html: "The documented hosted model accepts audio and video but returns text." }, { type: "subheading", text: "Does it support tools and web search?" }, { type: "paragraph", html: "Yes. Alibaba documents custom function calling and the Responses built-in web_search tool." }, { type: "subheading", text: "What is the context window?" }, { type: "paragraph", html: "One million tokens, subject to separate documented input and output ceilings." }] }
    ],
    sources: [{ label: "Alibaba Cloud Model Studio — Qwen3.8-Omni-Flash", url: "https://www.alibabacloud.com/help/en/model-studio/qwen3-8-omni-flash" }, { label: "Alibaba Cloud Model Studio — Rate limiting", url: "https://www.alibabacloud.com/help/en/model-studio/rate-limit" }, { label: "Alibaba Cloud Model Studio — Qwen-Omni", url: "https://www.alibabacloud.com/help/en/model-studio/qwen-omni" }], relatedPaths: ["/blog/qwen3-8-omni-flash-api"]
  },
  {
    status: "published", articleType: "supporting", parentSlug: "qwen3-8-omni-flash", cluster: "Qwen3.8-Omni-Flash",
    targetSearchIntent: "Implement Qwen3.8-Omni-Flash through Alibaba Cloud Model Studio for multimodal analysis, reasoning, function calling and Responses web search", targetQuery: "Qwen3.8 Omni Flash API",
    slug: "qwen3-8-omni-flash-api", title: "How to Use Qwen3.8 Omni Flash API: Multimodal Requests, Tools & Web Search", metaTitle: "How to Use Qwen3.8 Omni Flash API: Multimodal + Tools", metaDescription: "Use Qwen3.8-Omni-Flash through Alibaba Model Studio with text, images, audio and video, reasoning, function calls, Responses web search and caching.", h1: "How to Use Qwen3.8 Omni Flash API for Multimodal Analysis and Tools", excerpt: "An implementation-focused guide to Qwen3.8-Omni-Flash in Alibaba Cloud Model Studio, including multimodal input, reasoning, tools, web search and caching.", category: "AI", author: "Mayank", datePublished: "2026-09-21", dateModified: "2026-09-21", ogAlt: "Qwen3.8 Omni Flash API workflow with multimodal input and tools",
    sections: [
      { id: "region", title: "1. Choose a supported Model Studio region", blocks: [{ type: "paragraph", html: "Alibaba currently lists Beijing, Singapore, Hong Kong, Tokyo, Frankfurt and Virginia. Use an API key from the same region as the endpoint you call, and check the current regional rate-limit table before production deployment." }] },
      { id: "model", title: "2. Use the exact model ID", blocks: [{ type: "paragraph", html: "The documented hosted model ID is qwen3.8-omni-flash. Do not assume similarly named Qwen3.8 models expose the same modalities, limits or tools." }] },
      { id: "api-mode", title: "3. Pick Chat Completions or Responses", blocks: [{ type: "paragraph", html: "Alibaba documents both APIs. Chat Completions fits message-oriented integrations and exposes documented multichannel-audio options. Responses supports the provider's built-in web_search tool and Responses Session caching." }] },
      { id: "multimodal", title: "4. Send multimodal input", blocks: [{ type: "paragraph", html: "The model accepts text, images, audio and video and returns text. A request can combine instructions with screenshots, recordings or video for analysis. Alibaba documents audio input tokenization at seven tokens per second for this model." }] },
      { id: "reasoning", title: "5. Control reasoning and long context", blocks: [{ type: "paragraph", html: "Thinking is enabled by default with adjustable reasoning effort. The context window is 1M tokens; maximum input is 991,808 tokens without thinking or 983,616 with thinking, and maximum output is 131,072 tokens." }] },
      { id: "tools", title: "6. Add custom functions and web search", blocks: [{ type: "paragraph", html: "Alibaba explicitly documents custom function calling. Responses also exposes built-in web search as web_search. Custom functions connect to actions your application defines; the application must validate arguments and enforce authorization before side effects." }] },
      { id: "cache", title: "7. Use caching for repeated long context", blocks: [{ type: "paragraph", html: "Qwen3.8-Omni-Flash supports automatic implicit context caching and Responses Session caching, useful when a large document or media context is reused across turns. Verify current billing rules before building cost assumptions around caching." }] },
      { id: "limits", title: "8. Build within regional limits", blocks: [{ type: "paragraph", html: "The current Qwen-Omni rate-limit table lists 30,000 RPM. Hong Kong, Tokyo, Frankfurt and Virginia list 2,000,000 TPM, while Singapore and Beijing show dynamic token limits. Design retry and backoff behavior rather than treating a ceiling as guaranteed throughput." }] },
      { id: "continue", title: "Continue Reading", blocks: [{ type: "paragraph", html: "Read the main Qwen3.8-Omni-Flash guide for the broader model overview, availability, limits and verification notes." }] }
    ],
    sources: [{ label: "Alibaba Cloud Model Studio — Qwen3.8-Omni-Flash", url: "https://www.alibabacloud.com/help/en/model-studio/qwen3-8-omni-flash" }, { label: "Alibaba Cloud Model Studio — Rate limiting", url: "https://www.alibabacloud.com/help/en/model-studio/rate-limit" }, { label: "Alibaba Cloud Model Studio — Qwen-Omni", url: "https://www.alibabacloud.com/help/en/model-studio/qwen-omni" }], relatedPaths: ["/blog/qwen3-8-omni-flash"]
  }
];
