import type { BlogArticle } from "./blog-types.ts";

export const gemini38TtsArticles: BlogArticle[] = [
  {
    status: "published",
    articleType: "main",
    cluster: "Gemini 3.8 Flash TTS",
    targetSearchIntent: "Broad overview of Gemini 3.8 Flash TTS and Flash-Lite TTS: release, features, voice design and replication, availability, safeguards, API status and use cases",
    targetQuery: "Gemini 3.8 Flash TTS",
    slug: "gemini-3-8-flash-tts",
    title: "Gemini 3.8 Flash TTS: API, Voice Cloning & Features",
    metaTitle: "Gemini 3.8 Flash TTS: API, Voice Cloning & Features",
    metaDescription: "Google launched Gemini 3.8 Flash TTS and Flash-Lite TTS with custom voice design, consent-based voice replication, dual-speaker dialogue and 100+ languages.",
    h1: "Gemini 3.8 Flash TTS: Voice Design, API, Cloning & Features",
    excerpt: "A verified guide to Gemini 3.8 Flash TTS, Flash-Lite TTS, voice design, replication, multilingual speech and provenance.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-25",
    dateModified: "2026-09-25",
    ogAlt: "Gemini 3.8 Flash TTS voice design, multilingual speech and dual-speaker audio",
    sections: [
      { id: "launch", title: "What is Gemini 3.8 Flash TTS?", blocks: [
        { type: "paragraph", html: "Google announced Gemini 3.8 Flash TTS and Gemini 3.8 Flash-Lite TTS on September 23, 2026. Flash TTS is positioned for creative voice design and directed performances, while Flash-Lite targets higher-volume, cost-efficient speech generation." },
        { type: "paragraph", html: "Both models are rolling out through the Gemini API and Google AI Studio. Current Gemini API documentation lists the model IDs gemini-3.8-flash-tts and gemini-3.8-flash-lite-tts and distinguishes TTS from the interactive Gemini Live API." }
      ]},
      { id: "voices", title: "Voice design, replication and performances", blocks: [
        { type: "paragraph", html: "Flash TTS supports prompt-designed voices and a large production voice library. Google also documents line-level performance direction, non-verbal vocal events and native two-speaker scene staging for scripts such as podcasts and dialogue." },
        { type: "paragraph", html: "Voice replication can create a reusable vocal profile from about 30 seconds of reference audio, but Google requires the user to own the voice or have rights to use it and requires a matching verbal-consent recording from the voice owner." }
      ]},
      { id: "languages", title: "Languages, voices and long-form use", blocks: [
        { type: "paragraph", html: "Google's launch announcement says the family supports more than 100 languages and dialects and offers more than 2,000 production-ready voices. Exact voice availability can vary by model or product surface, so teams should verify the live API documentation for localization work." },
        { type: "paragraph", html: "Google positions the models for podcasts, audiobooks, games, dubbing and voice agents. Claims about long-form consistency are vendor claims rather than guarantees; production teams should test timbre, pronunciation and pacing on their own scripts." }
      ]},
      { id: "safety", title: "SynthID, C2PA and regional restrictions", blocks: [
        { type: "paragraph", html: "Google says audio generated by Gemini Audio models carries SynthID watermarking. Replicated voices additionally use C2PA credentials, while consent verification is built into the replication workflow." },
        { type: "paragraph", html: "At launch, AI Studio voice replication is unavailable in Illinois, Texas, the EEA, the United Kingdom, Switzerland and India. This restriction is specific to the documented replication workflow and should be rechecked as rollout changes." }
      ]},
      { id: "availability", title: "API status, benchmarks and caveats", blocks: [
        { type: "paragraph", html: "The Gemini API speech-generation guide is the current implementation authority for model IDs and request structure. Pricing, quotas and regional access are time-sensitive, so this article does not infer missing commercial details from older TTS models." },
        { type: "paragraph", html: "Google reports strong scores on Hume AI voice-design and accent benchmarks and says Flash TTS and Flash-Lite perform strongly in blind preference testing. Those are Google-reported launch results and should remain attributed rather than being treated as universal superiority claims." }
      ]}
    ],
    sources: [
      { label: "Google — Gemini 3.8 text-to-speech launch", url: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-8-text-to-speech/" },
      { label: "Google AI for Developers — Text-to-speech generation", url: "https://ai.google.dev/gemini-api/docs/speech-generation" },
      { label: "Google AI for Developers — Gemini API documentation", url: "https://ai.google.dev/gemini-api/docs" }
    ],
    relatedPaths: ["/blog/gemini-3-8-flash-tts-voice-cloning"]
  },
  {
    status: "published",
    articleType: "supporting",
    cluster: "Gemini 3.8 Flash TTS",
    targetSearchIntent: "Understand and safely use Gemini 3.8 Flash TTS voice replication, including the 30-second sample, consent verification, regional restrictions and provenance safeguards",
    targetQuery: "Gemini 3.8 Flash TTS voice cloning",
    parentSlug: "gemini-3-8-flash-tts",
    slug: "gemini-3-8-flash-tts-voice-cloning",
    title: "Gemini 3.8 Flash TTS Voice Replication: Consent, Availability & Safety",
    metaTitle: "Gemini 3.8 Flash TTS Voice Cloning: Consent & Availability",
    metaDescription: "How Gemini 3.8 Flash TTS voice replication works: 30-second samples, verbal consent verification, regional restrictions, SynthID and C2PA safeguards.",
    h1: "Gemini 3.8 Flash TTS Voice Replication: How It Works & Where It's Available",
    excerpt: "How Gemini voice replication uses a short reference sample, consent verification and provenance controls.",
    category: "AI",
    author: "Project Monet Editorial Team",
    datePublished: "2026-09-25",
    dateModified: "2026-09-25",
    ogAlt: "Gemini voice replication workflow from reference audio through consent to a reusable voice profile",
    sections: [
      { id: "replication", title: "What Google means by voice replication", blocks: [
        { type: "paragraph", html: "Gemini 3.8 Flash TTS can create a reusable vocal profile from about 30 seconds of a speaker's reference audio. Google calls the feature voice replication and separates it from prompt-based voice design, which creates a new synthetic voice without copying a real speaker." },
        { type: "paragraph", html: "A short sample is a product input, not proof of permission. Google's documented workflow requires the user to own the voice or have rights to use it before a replicated profile is created." }
      ]},
      { id: "consent", title: "The separate verbal-consent step", blocks: [
        { type: "paragraph", html: "Google requires a verbal consent recording from the voice owner and verifies that the consent speaker matches the person in the reference audio. This makes the launch materially different from an unrestricted upload-and-clone workflow." },
        { type: "paragraph", html: "Production teams should preserve evidence of rights and consent independently of the technical profile. API support does not remove contractual, platform or disclosure obligations around synthetic speech." }
      ]},
      { id: "availability", title: "Where voice replication is unavailable", blocks: [
        { type: "paragraph", html: "At launch, Google says AI Studio voice replication is unavailable in Illinois, Texas, the European Economic Area, the United Kingdom, Switzerland and India. That list is time-sensitive and should be checked before deployment." },
        { type: "paragraph", html: "The restriction should not be generalized to every Gemini TTS capability. A user may have access to speech generation while the replication workflow itself remains unavailable in the relevant region or surface." }
      ]},
      { id: "provenance", title: "SynthID, C2PA and publishing safeguards", blocks: [
        { type: "paragraph", html: "Google says Gemini Audio outputs contain imperceptible SynthID watermarking, and replicated voices additionally use C2PA credentials. These provide provenance signals but do not substitute for permission or appropriate disclosure." },
        { type: "paragraph", html: "For fictional narrators or brand characters, a newly designed synthetic voice may avoid some identity-governance complexity. For a real replicated speaker, test similarity, multilingual behavior and long-form consistency only with consented material." }
      ]},
      { id: "workflow", title: "A practical, consent-first workflow", blocks: [
        { type: "paragraph", html: "Decide first whether a recognizable real voice is necessary, obtain rights, record a clean reference, complete the matching consent step, create the profile on a supported surface and test it on representative scripts." },
        { type: "paragraph", html: "Regional availability, model access, quotas and pricing can change. Voice Remix was announced as coming soon and should not be described as part of the currently verified replication workflow until Google documents its release." }
      ]}
    ],
    sources: [
      { label: "Google — Gemini 3.8 text-to-speech launch", url: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-8-text-to-speech/" },
      { label: "Google AI for Developers — Text-to-speech generation", url: "https://ai.google.dev/gemini-api/docs/speech-generation" },
      { label: "Google AI for Developers — Gemini API documentation", url: "https://ai.google.dev/gemini-api/docs" }
    ],
    relatedPaths: ["/blog/gemini-3-8-flash-tts"]
  }
];
