import type { SeoPage } from "./seo-content.ts";

const published = "2026-08-20";
const updated = "August 20, 2026";

export const phaseTwoCorePages: SeoPage[] = [
  {
    path: "/about",
    title: "About Project Monet and Mayank Harsh",
    metaTitle: "About Project Monet & Mayank Harsh | Website Studio",
    metaDescription: "Meet Mayank Harsh, the creator and hands-on builder behind Project Monet, and learn how the studio approaches websites, proof, ownership and client decisions.",
    eyebrow: "The person behind the studio",
    heading: "Built by someone who studies why people stop, trust and act.",
    intro: "Project Monet is a focused website studio led by Mayank Harsh in Gurgaon, India. It combines visual judgement, audience psychology and hands-on web development to help local businesses present themselves more clearly online.",
    quickAnswer: "Mayank Harsh is the founder and hands-on creative behind Project Monet. Before building the studio, he grew creator communities to more than 102,000 combined followers and 35 million organic views. Those are founder results—not Project Monet client results—and they inform how the studio thinks about attention, clarity and trust.",
    kind: "profile",
    updated,
    published,
    image: { src: "/work/mayank-harsh.jpg", alt: "Mayank Harsh personal portfolio website preview", position: "center 28%" },
    sections: [
      {
        title: "A creator's view of the first few seconds",
        paragraphs: [
          "Mayank built two creator-led Instagram communities from zero in poetry, literature and music. Across that work, the accounts reached more than 102,000 combined followers, 35 million organic views and several original trend formats. One reel crossed 9.5 million views, while a music-led format reached a larger audience on the second account.",
          "That background does not make a website successful by itself. It does create a useful instinct: a person arriving on a page needs an immediate reason to stay, a coherent visual world and a clear next step. Project Monet applies that instinct without turning a business website into a social feed.",
        ],
      },
      {
        title: "Visual taste backed by practical systems",
        paragraphs: [
          "The work crosses creative direction, social strategy, copy, analytics and front-end development. Mayank has completed Harvard's CS50x and works hands-on with modern web tools, search foundations, analytics and deployment rather than treating design as a static mockup passed to someone else.",
          "Project Monet therefore looks at the whole path: how the page feels, whether the words are accurate, how it behaves on a phone, whether enquiries can be measured, and whether the owner receives the relevant access after payment.",
        ],
        bullets: ["Creative direction and visual systems", "Clear, human website copy", "Responsive web design and development", "Search and analytics foundations", "Conversion paths for calls, WhatsApp and forms", "Documented ownership and handover"],
      },
      {
        title: "Why Project Monet begins with a concept",
        paragraphs: [
          "A business owner can struggle to judge a website from a proposal full of adjectives. Project Monet's free homepage concept is a smaller, more concrete way to test the direction before the paid project begins.",
          "The concept is deliberately limited. It is not a finished website, a revision round or a transferable design. If the direction fits, the pages, features, content responsibilities, price and timeline are confirmed in writing before production starts.",
        ],
      },
      {
        title: "The operating principles",
        bullets: ["Show the work without inventing the outcome", "Label concepts and speculative work honestly", "Use founder metrics only as founder credentials", "Keep pricing and exclusions understandable", "Give the client ownership after final payment", "Prefer a useful answer over agency jargon", "Never guarantee rankings, leads, sales or revenue"],
        paragraphs: ["Project Monet is still building its body of paid client evidence. Until permission-based case studies exist, the Work library shows design and strategy concepts as concepts. That distinction matters more than borrowing credibility the studio has not earned."],
      },
      {
        title: "Where the studio works",
        paragraphs: ["Project Monet is based in Gurgaon and works with businesses in India and internationally. The initial focus is local and service businesses whose website affects trust: clinics, restaurants, interiors, construction, fitness, real estate, ecommerce and professional services.", "The studio can work remotely, but it does not pretend every project needs the same package. A focused one-page site, a multi-page business website and a growth-oriented content structure solve different problems."],
      },
    ],
    faqs: [
      { question: "Is Project Monet a large agency?", answer: "No. It is currently a founder-led studio. Mayank leads the creative and website direction, and any specialist support should be disclosed when it materially affects a project." },
      { question: "Are the audience numbers Project Monet client results?", answer: "No. They are Mayank's personal creator results and are stated only as founder background. Client outcomes will be published separately only with evidence and permission." },
      { question: "Does Mayank personally work on the websites?", answer: "Yes. Project Monet is currently hands-on and founder-led, covering direction, content structure, design, development and launch coordination according to the agreed scope." },
      { question: "Where is Project Monet based?", answer: "The studio is based in Gurgaon, India, and can work with businesses elsewhere in India and internationally through a remote process." },
    ],
    relatedPaths: ["/work/shop-co-ecommerce-concept", "/services/web-design-for-local-businesses", "/how-it-works", "/free-website-demo"],
  },
];

export const workPages: SeoPage[] = [
  {
    path: "/work/shop-co-ecommerce-concept",
    title: "Shop Co Ecommerce Website Concept",
    metaTitle: "Shop Co Ecommerce Website Concept | Project Monet Work",
    metaDescription: "Explore the Shop Co ecommerce concept: a fashion storefront built around product discovery, clear categories, promotions and a focused path to purchase.",
    eyebrow: "Concept breakdown · Ecommerce",
    heading: "A fashion storefront that makes browsing feel immediate.",
    intro: "Shop Co is a speculative ecommerce interface created to demonstrate a retail direction. It is not presented as a paid client project and it does not claim sales, conversion or revenue results.",
    quickAnswer: "The Shop Co concept uses a clear retail hierarchy: promotional message, recognisable categories, product-led cards and repeated shopping actions. Its purpose is to show how an ecommerce homepage can move a visitor from arrival to product discovery without hiding the commercial path behind decoration.",
    kind: "work",
    updated,
    published,
    image: { src: "/work/shop-co.jpg", alt: "Shop Co ecommerce website concept preview", position: "center top" },
    demo: { label: "Open the Shop Co live concept", url: "https://ecommerce-figma-build.vercel.app/shop-co.html" },
    sections: [
      { title: "The customer journey this concept explores", paragraphs: ["A fashion visitor may arrive with only a loose intention: browse new pieces, compare a category or check whether the store feels credible. The homepage therefore begins with merchandise and positioning rather than a long company introduction.", "The page is organised to let shoppers scan before they commit. Category routes and product previews give several useful entry points while the visual system keeps them inside one coherent brand world."], },
      { title: "Design decisions", bullets: ["Strong promotional hero with an immediate shopping action", "Product cards that keep imagery, name and price easy to compare", "Category groupings for quicker discovery", "Consistent spacing and typography across retail modules", "Responsive sections designed for narrow screens", "A restrained palette that leaves attention on the merchandise"], },
      { title: "What a production store would still require", paragraphs: ["A real ecommerce build needs more than this public concept: product data, inventory rules, variants, taxes, shipping, payments, order communication, returns and account policies all need to be selected and tested.", "The visual direction can guide that system, but it cannot replace operational decisions. A production scope would also define analytics, consent, accessibility, performance budgets and who maintains catalog information."], },
      { title: "How this direction could be adapted", paragraphs: ["The same structure could support apparel, jewellery, lifestyle products or a focused catalogue, but the content should never be swapped mechanically. Product photography, buying anxieties, sizing information, delivery expectations and trust signals differ by category.", "Project Monet would use a business's actual catalogue and policies during a paid build rather than presenting concept products as real inventory."], },
    ],
    faqs: [
      { question: "Is Shop Co a Project Monet client?", answer: "No. Shop Co is a clearly labelled ecommerce concept used to demonstrate design and customer-journey thinking." },
      { question: "Does the live concept process real orders?", answer: "No claim is made that the public concept is a production store. Payments, inventory and fulfilment require a separately scoped ecommerce implementation." },
      { question: "Can this design be copied for another store?", answer: "It can inform a direction, but a paid store should be adapted around the real brand, catalogue, customers and operational requirements rather than copied without context." },
      { question: "Can Project Monet build ecommerce websites?", answer: "Yes, subject to the chosen platform, catalogue size, payment, shipping and management requirements. Ecommerce is quoted after those dependencies are understood." },
    ],
    relatedPaths: ["/industries/ecommerce", "/work/restaurant-website-concept", "/resources/prepare-before-hiring-web-designer", "/free-website-demo"],
  },
  {
    path: "/work/construction-company-website-concept",
    title: "Construction Company Website Concept",
    metaTitle: "Construction Website Concept | Project Monet Work",
    metaDescription: "See a construction-company website concept built to communicate capability, project categories, delivery confidence and a clear route to discuss new work.",
    eyebrow: "Concept breakdown · Construction",
    heading: "Make capability visible before asking for the enquiry.",
    intro: "This speculative construction-company concept explores how a high-consideration service can present scale, process and project experience without relying on generic claims such as quality and excellence.",
    quickAnswer: "The construction concept puts capability, project imagery and a structured enquiry path ahead of slogans. It demonstrates how a company can help prospects understand what it builds, where it works and what happens after first contact. It is a design concept, not evidence of completed Project Monet client work.",
    kind: "work",
    updated,
    published,
    image: { src: "/work/construction.jpg", alt: "Construction company website concept preview", position: "center top" },
    demo: { label: "Open the construction live concept", url: "https://construction-azure-five.vercel.app/" },
    sections: [
      { title: "The trust problem", paragraphs: ["Construction decisions carry cost, schedule and execution risk. A prospect needs more than a dramatic building photograph; they need to know the category of work, service area, operating process and evidence behind the claims.", "The concept uses visual scale to earn attention, then moves toward practical explanations. A production version would replace illustrative material with permission-based projects, credentials and contact details."], },
      { title: "The page hierarchy", bullets: ["Immediate statement of construction focus", "Project-led visual proof area", "Service or capability categories", "Process language that explains the next step", "Contact action suited to project enquiries", "Mobile layouts that preserve the visual impact"], },
      { title: "What genuine proof should look like", paragraphs: ["Real project pages should name the type of work, location when permitted, scope, constraints and the company's role. A gallery without context can look impressive while telling the buyer very little.", "Certifications, registrations, safety information, partner logos and testimonials should appear only when current, relevant and permitted. Project Monet would not invent a project value, completion date or client quotation to fill the layout."], },
      { title: "Production considerations", paragraphs: ["A live construction site may need separate pages for residential, commercial, renovation or turnkey work; downloadable capability documents; hiring; tender enquiries; and multiple office locations.", "The final scope depends on the actual sales process. A business that qualifies projects by phone needs a different form from one that requires drawings, budget range and a formal brief."], },
    ],
    faqs: [
      { question: "Is this an actual construction client website?", answer: "It is a speculative concept and is labelled accordingly. It does not represent a client relationship or business outcome." },
      { question: "Can real project case studies be added?", answer: "Yes. They should use accurate project information, approved photography and permission to identify the client or location where relevant." },
      { question: "Should every construction service have its own page?", answer: "Only when the service has distinct buyer questions and enough accurate information to justify a useful page. A thin list of near-duplicate pages is not helpful." },
      { question: "Can the enquiry form collect project details?", answer: "Yes. Useful fields may include project type, location, stage, estimated scope and preferred contact route, provided the business can protect and act on that information." },
    ],
    relatedPaths: ["/industries/construction-companies", "/work/interior-design-website-concept", "/resources/write-small-business-website-brief", "/free-website-demo"],
  },
  {
    path: "/work/ahs-home-services-website-concept",
    title: "AHS Home Services Website Concept",
    metaTitle: "AHS Home Services Website Concept | Project Monet Work",
    metaDescription: "Explore the AHS home-services website concept, designed around urgent service discovery, trust, coverage clarity and an uncomplicated route to request help.",
    eyebrow: "Concept breakdown · Home services",
    heading: "When help is urgent, the page should feel uncomplicated.",
    intro: "AHS is a speculative home-services concept created to test a direct, mobile-first service journey. It does not represent a client engagement or claim completed jobs, ratings or lead results.",
    quickAnswer: "The AHS concept prioritises the service need, availability and contact path. It reduces the number of decisions between a visitor recognising a household problem and requesting help, while leaving room for service areas, trust information and realistic expectations.",
    kind: "work",
    updated,
    published,
    image: { src: "/work/ahs.jpg", alt: "AHS home services website concept preview", position: "center top" },
    demo: { label: "Open the AHS live concept", url: "https://ahs-teal.vercel.app/" },
    sections: [
      { title: "Designed for a practical moment", paragraphs: ["Someone looking for plumbing, electrical or repair help may be on a phone and under time pressure. The website should identify the services and coverage quickly instead of making the visitor decode an abstract brand message.", "The concept keeps a prominent request path near the service information. A real business would also publish accurate hours, response expectations and emergency limitations rather than implying constant availability."], },
      { title: "Useful components", bullets: ["Clear service categories", "Primary call or request action", "Visible location and coverage information", "Trust section for verified qualifications or guarantees", "Simple explanation of the booking process", "Frequently asked questions about access, pricing and timing"], },
      { title: "What must come from the business", paragraphs: ["The provider must supply real service descriptions, areas served, hours, licences where applicable, pricing approach and any guarantee terms. Original team or work photography is stronger than a library of anonymous stock technicians.", "If customer reviews are used, they need permission and a reliable source. The concept intentionally makes no rating or volume claim."], },
      { title: "How conversion should be measured", paragraphs: ["A production website can distinguish taps to call, WhatsApp starts and completed enquiry forms. Those events reveal whether people reach the intended actions, but they do not prove that every enquiry becomes a customer.", "Tracking should respect consent choices and avoid sending form contents or other personally identifiable information to analytics platforms."], },
    ],
    faqs: [
      { question: "Is AHS a real client case study?", answer: "No. It is a home-services concept and contains no claim of client results." },
      { question: "Can this support several service areas?", answer: "Yes, when each area page contains genuine availability, contact and service information. Mass-produced location pages should be avoided." },
      { question: "Can visitors book a time slot?", answer: "A booking flow can be integrated when the provider's calendar, staffing and cancellation rules are known. It is not assumed in the concept." },
      { question: "What is the best primary action for home services?", answer: "It depends on how the team responds. Calling may fit urgent work, while WhatsApp or a structured form can suit quotations and non-urgent visits." },
    ],
    relatedPaths: ["/industries/home-services", "/resources/website-more-calls-whatsapp-enquiries", "/work/construction-company-website-concept", "/free-website-demo"],
  },
  {
    path: "/work/dental-clinic-website-concept",
    title: "Dental Clinic Website Concept",
    metaTitle: "Dental Clinic Website Concept | Project Monet Work",
    metaDescription: "Review a dental-clinic website concept focused on practitioner trust, treatment clarity, clinic information and a responsible appointment journey.",
    eyebrow: "Concept breakdown · Dental",
    heading: "Clinical trust without turning care into advertising theatre.",
    intro: "The 0900 Dental concept demonstrates a clear clinic direction using practitioner, treatment and appointment information. It is speculative work, not a clinic client case study, and it makes no medical or patient-outcome claim.",
    quickAnswer: "The dental concept organises the page around the questions a patient can reasonably answer online: who practises there, which treatments are discussed, where the clinic is and how to request an appointment. Diagnosis, suitability, price and outcomes still require appropriate professional assessment.",
    kind: "work",
    updated,
    published,
    image: { src: "/work/0900-dental.jpg", alt: "0900 Dental clinic website concept preview", position: "center top" },
    demo: { label: "Open the dental live concept", url: "https://dentist-peach-tau.vercel.app/" },
    sections: [
      { title: "The patient questions behind the layout", paragraphs: ["A person may arrive with anxiety, an unfamiliar treatment name or a need to find an appointment quickly. The website should reduce avoidable uncertainty without diagnosing a condition or promising a result.", "The concept balances clinical presentation with accessible language. A real version would use the clinic's verified practitioner details, original facilities and approved treatment information."], },
      { title: "Trust elements worth earning", bullets: ["Named practitioners and accurate qualifications", "Clear clinic address, hours and contact methods", "Treatment explanations reviewed by the clinic", "Original, permission-based clinic photography", "Appointment expectations and emergency guidance", "Privacy-conscious enquiry forms"], },
      { title: "Responsible content boundaries", paragraphs: ["Marketing copy should not present every visitor as suitable for a procedure, guarantee a painless experience or imply a result that depends on examination and follow-up. Before-and-after media requires consent and should not create a misleading universal expectation.", "Project Monet provides website structure and communication support; the qualified clinic remains responsible for clinical accuracy, professional rules and patient communication."], },
      { title: "From concept to production", paragraphs: ["A production clinic site may expand into practitioner profiles, treatment pages, appointment integration, multilingual information, accessibility improvements and location-specific directions.", "The final path should match the clinic's actual workflow. If appointments are only confirmed after a call, the button should say request an appointment rather than promise a confirmed booking."], },
    ],
    faqs: [
      { question: "Is 0900 Dental a Project Monet client?", answer: "No. The page is a speculative concept and is not presented as client work or proof of clinic results." },
      { question: "Can Project Monet write treatment advice?", answer: "Project Monet can structure and edit supplied information, but clinical content should be reviewed and approved by an appropriately qualified practitioner." },
      { question: "Can online booking be included?", answer: "Yes, if the clinic chooses a suitable system and defines availability, confirmation, cancellation and privacy requirements." },
      { question: "Should treatment prices appear online?", answer: "The clinic should decide based on accuracy and professional obligations. When final cost depends on examination, the page should explain that limitation clearly." },
    ],
    relatedPaths: ["/industries/dentists", "/industries/clinics", "/resources/local-business-website-sections", "/free-website-demo"],
  },
  {
    path: "/work/interior-design-website-concept",
    title: "Interior Design Website Concept",
    metaTitle: "Interior Design Website Concept | Project Monet Work",
    metaDescription: "Explore an interior-design website concept that uses project-led storytelling, service clarity and an intentional enquiry path without fabricating client proof.",
    eyebrow: "Concept breakdown · Interior design",
    heading: "Let the spaces lead, then explain how the work happens.",
    intro: "This interior-design concept explores a calm, editorial direction for presenting spaces and services. It is a speculative demo, not a claim that Project Monet designed the featured interiors or produced client results.",
    quickAnswer: "The concept gives visual work enough room to establish taste, then adds the practical information needed to turn admiration into an enquiry: project type, services, process and contact route. A production site would use the studio's own licensed photography and accurate project context.",
    kind: "work",
    updated,
    published,
    image: { src: "/work/interior.jpg", alt: "Interior design website concept preview", position: "center top" },
    demo: { label: "Open the interior live concept", url: "https://interior-three-omega.vercel.app/" },
    sections: [
      { title: "An editorial rhythm for visual work", paragraphs: ["Interior portfolios can become dense mosaics where every project competes at once. This direction uses scale, spacing and a restrained typographic system so each space has a moment and the brand feels considered.", "The visual pause is not an excuse to hide business information. Service types, location, process and enquiry expectations still need clear language."], },
      { title: "The structure", bullets: ["Project-led opening image and positioning", "Curated portfolio rather than an endless gallery", "Services separated by real scope", "Process explanation from consultation to delivery", "Designer or studio introduction", "Enquiry path that asks for useful project context"], },
      { title: "Photography and ownership", paragraphs: ["The business should use images it owns or has permission to publish. Each project can include location, type, design role, constraints and scope when the client has approved disclosure.", "Stock imagery can communicate a temporary mood during concept work, but it should not be presented as a completed studio project. The final site should make that distinction unmistakable."], },
      { title: "Qualifying the right enquiry", paragraphs: ["Interior enquiries often need more context than a name and phone number. A thoughtful form can ask for project type, location, approximate size, desired service and stage without becoming a thirty-question barrier.", "The studio should decide which information genuinely helps the first conversation. Budget questions can be useful when phrased carefully and supported by an explanation of what the range means."], },
    ],
    faqs: [
      { question: "Are the interiors shown Project Monet projects?", answer: "No. This is a website-design concept, and it does not claim ownership of the interior projects or client outcomes shown in the demo direction." },
      { question: "Can a real portfolio replace the concept images?", answer: "Yes. Original, permission-based work should become the centre of a production interior-design website." },
      { question: "Should every project have its own page?", answer: "Selected projects benefit from deeper stories when there is meaningful context. A smaller practice can begin with a curated portfolio and expand later." },
      { question: "Can the site collect detailed project briefs?", answer: "Yes. The form should collect only information the studio needs and can protect, with a clear privacy notice and sensible follow-up process." },
    ],
    relatedPaths: ["/industries/interior-designers", "/work/construction-company-website-concept", "/resources/write-small-business-website-brief", "/free-website-demo"],
  },
  {
    path: "/work/restaurant-website-concept",
    title: "Restaurant Website Concept",
    metaTitle: "Restaurant Website Concept | Project Monet Work",
    metaDescription: "See a restaurant website concept built around atmosphere, a mobile-readable menu path, practical visit information and direct reservation or ordering actions.",
    eyebrow: "Concept breakdown · Restaurant",
    heading: "Atmosphere should invite the visit—not obscure the menu.",
    intro: "This speculative restaurant concept combines a strong visual mood with practical dining information. It is not a client case study and makes no claim about bookings, orders, reviews or revenue.",
    quickAnswer: "The restaurant concept uses food and space imagery to establish atmosphere, then keeps the customer decisions visible: view the menu, check location and hours, and choose the correct reservation or ordering route. The visual identity supports those actions instead of replacing them.",
    kind: "work",
    updated,
    published,
    image: { src: "/work/restaurant.jpg", alt: "Restaurant website concept preview", position: "center top" },
    demo: { label: "Open the restaurant live concept", url: "https://restaurant-tan-eta.vercel.app/" },
    sections: [
      { title: "A fast mobile decision", paragraphs: ["Restaurant visitors often arrive with a small set of urgent questions: what kind of food is served, what does it cost, is the venue open, where is it and how do I book or order? The page should answer those questions even if the brand direction is cinematic.", "The concept places atmosphere and action together. A production version would replace illustrative details with the restaurant's current menu, hours, address, dietary information and contact workflow."], },
      { title: "What the direction prioritises", bullets: ["A distinctive first impression", "A clear route to the menu", "Visible reservation or ordering action", "Current hours and location", "Food and venue photography with permission", "Mobile layouts suited to quick decisions"], },
      { title: "Menus should remain usable", paragraphs: ["A designed PDF can remain downloadable, but the essential menu should also be legible on a phone. Text inside a large image is hard to update, search and navigate.", "If dishes and prices change frequently, the website needs an editing workflow the restaurant can maintain. A beautiful menu that is routinely wrong damages trust."], },
      { title: "Connecting external systems", paragraphs: ["A restaurant may already use a reservation, delivery or ordering platform. The site can route to those systems cleanly instead of rebuilding them without a business reason.", "Direct ordering, payments, table inventory, loyalty and gift cards create a larger technical and operational scope. They should be confirmed before the visual design implies a capability the restaurant does not actually offer."], },
    ],
    faqs: [
      { question: "Is this a real restaurant client website?", answer: "No. It is a speculative Project Monet concept and contains no claim of bookings, orders or client results." },
      { question: "Can the website link to an existing delivery platform?", answer: "Yes. A clear external route may be the simplest option when the restaurant already has a working ordering or reservation system." },
      { question: "Can the restaurant update its own menu?", answer: "Yes, if a suitable content-management workflow is included in the scope. The update frequency and responsible person should be decided before launch." },
      { question: "Is professional photography included?", answer: "Not by default. The restaurant can supply original licensed media, or photography and sourcing can be scoped separately." },
    ],
    relatedPaths: ["/industries/restaurants", "/work/shop-co-ecommerce-concept", "/resources/website-more-calls-whatsapp-enquiries", "/free-website-demo"],
  },
];

export const phaseTwoResourcePages: SeoPage[] = [
  {
    path: "/resources/one-page-vs-multi-page-website",
    title: "One-Page vs Multi-Page Website: Which Does a Small Business Need?",
    metaTitle: "One-Page vs Multi-Page Website for Small Businesses",
    metaDescription: "Compare one-page and multi-page websites by scope, customer journey, search needs, maintenance and cost so your business chooses the useful structure.",
    eyebrow: "Website structure guide",
    heading: "Choose the smallest structure that explains the business properly.",
    intro: "A one-page website is not automatically basic, and a multi-page website is not automatically better. The useful choice depends on how many distinct questions customers need answered and how the business expects people to find the site.",
    quickAnswer: "Choose a one-page website when the business has a focused offer, one main audience and one primary action. Choose a multi-page website when services, locations, practitioners, proof or search topics need separate explanations. Do not add pages merely to look established; add them when they serve a distinct customer or search decision.",
    kind: "guide",
    updated,
    published,
    sections: [
      { title: "When one page is enough", paragraphs: ["A focused local service, event, personal practice or early-stage business may be able to explain the complete decision on one well-structured page. The visitor can understand the offer, proof, process, location and contact route without leaving the flow.", "One page also means fewer content dependencies at launch. It still needs thoughtful mobile design, accurate copy, accessibility, analytics and technical search foundations."], bullets: ["One main service or tightly related offer", "One location or uncomplicated service area", "A short buying decision", "Limited but genuine proof", "One primary call, WhatsApp or form action"], },
      { title: "When separate pages become useful", paragraphs: ["A multi-page structure helps when customers compare several substantial services, need practitioner or project detail, or search for specific questions that cannot be answered responsibly in a short section.", "Separate pages also make sharing easier: a prospect can receive the exact service or case study relevant to the conversation rather than a link to the top of a long homepage."], bullets: ["Distinct services with different buyers or requirements", "Several locations with genuinely different information", "Treatment, project or product depth", "Resources that answer recurring pre-sale questions", "A deliberate organic search strategy"], },
      { title: "SEO is not a page-count contest", paragraphs: ["A multi-page site creates more opportunities only when each page is useful and distinct. Several thin pages that repeat the same offer with swapped keywords can compete with one another and weaken the experience.", "A strong one-page site can still be indexed for its relevant topic. A multi-page site becomes valuable when the business can maintain accurate, original content and link the pages into a coherent system."], },
      { title: "A practical decision test", bullets: ["List the questions customers ask before contacting you", "Group questions that belong to one decision", "Identify services that require materially different proof", "Decide which page you would send during a real sales conversation", "Check whether the business can keep every proposed page current", "Start smaller if the content does not yet exist"], },
      { title: "Project Monet's starting point", paragraphs: ["The Starter package is designed for a focused one-page presence. The Business and Growth packages support deeper structures when the scope justifies them.", "The final page count is agreed in writing. Extra pages, advanced copy, integrations and ongoing content work are not silently assumed from the package name."], },
    ],
    faqs: [
      { question: "Can a one-page website rank in search?", answer: "It can be indexed and rank for relevant queries, but it has limited room to address several distinct search intents. Quality, relevance, competition and authority still matter." },
      { question: "Is a multi-page website always more expensive?", answer: "Usually it requires more planning, content, design and testing, but complexity matters more than the number alone. Integrations can make a one-page project larger than a simple multi-page brochure site." },
      { question: "Can a one-page site expand later?", answer: "Yes. A good structure can become the homepage while priority services, projects or resources receive their own pages later." },
      { question: "How many pages should a local business begin with?", answer: "There is no universal number. Begin with the pages needed to explain the offer, establish trust and support the real customer journey without padding." },
    ],
    relatedPaths: ["/resources/landing-page-vs-website-small-business", "/pricing", "/resources/local-business-website-sections", "/resources/how-long-to-build-small-business-website", "/services/web-design-for-local-businesses"],
    sources: [{ label: "Google: Creating helpful, people-first content", url: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" }],
  },
  {
    path: "/resources/prepare-before-hiring-web-designer",
    title: "What to Prepare Before Hiring a Web Designer",
    metaTitle: "What to Prepare Before Hiring a Web Designer",
    metaDescription: "Prepare your goals, services, content, media, access, decision-maker and feature requirements before hiring a web designer or requesting a quote.",
    eyebrow: "Pre-project checklist",
    heading: "A clearer brief creates a clearer quote—and fewer expensive assumptions.",
    intro: "You do not need to arrive with a finished sitemap or technical specification. You do need enough business context for a designer to understand the problem, the customers and what must be true at launch.",
    quickAnswer: "Before hiring a web designer, prepare your business goals, priority services, customer questions, contact route, service area, real proof, available brand assets and required systems. Identify one final decision-maker and decide who will supply and approve copy, images and account access.",
    kind: "guide",
    updated,
    published,
    sections: [
      { title: "Start with the business problem", paragraphs: ["‘We need a modern website’ describes a preference, not the problem. Explain what is failing today: customers cannot understand the services, the current site looks untrustworthy, enquiries go to the wrong place or the business has no controlled web presence.", "A useful goal is observable without promising a result. For example: make the service areas clear, reduce repetitive pre-sale questions, or provide a credible page to send after a sales call."], },
      { title: "Collect the core facts", bullets: ["Official business name and contact details", "Services and the differences between them", "Locations or actual service area", "Opening or response hours", "Primary customer groups", "Qualifications, registrations or policies that can be verified", "Current website, Google profile and social links"], },
      { title: "Audit the content you already own", paragraphs: ["Gather the logo files, colours, fonts, photographs, product or project information, team profiles, testimonials and policy documents you can legally use. Mark anything outdated or awaiting permission.", "Do not assume the designer can lift images or copy from another business. Content creation, photography and licensing should be included in the quote when the business cannot supply suitable material."], },
      { title: "Name the systems and accounts involved", bullets: ["Domain registrar", "Hosting platform", "Business email", "Google Business Profile", "Analytics and Search Console", "Booking or calendar system", "Payment or ecommerce platform", "Customer relationship or enquiry system"], paragraphs: ["The business should know who owns each account and how access will be granted safely. Avoid sending passwords through casual messages when a platform supports roles or invitations."], },
      { title: "Prepare the approval process", paragraphs: ["Choose the person who can make final decisions and define how other feedback reaches them. Several stakeholders can contribute, but one consolidated response prevents a revision round from becoming a collection of conflicting preferences.", "Agree on who writes, reviews and legally approves sensitive claims. A designer can improve clarity; the business remains responsible for the accuracy of its services, prices, credentials and regulated information."], },
    ],
    faqs: [
      { question: "Do I need to write all website copy first?", answer: "Not always. Clarify whether copywriting is included. Even with a writer, the business must supply accurate facts, approvals and subject expertise." },
      { question: "Should I buy the domain before hiring a designer?", answer: "It is sensible to secure the right domain in a business-controlled account. The designer can help with technical setup without becoming the registrant owner." },
      { question: "What if I have no professional photos?", answer: "Discuss photography, licensed stock or a staged launch. Do not present unrelated stock images as your real team, facility or completed work." },
      { question: "How many examples should I send?", answer: "A small set is enough when you explain what you like or dislike about each. References should communicate direction, not instruct the designer to copy another site." },
    ],
    relatedPaths: ["/resources/web-design-agency-vs-freelancer-india", "/resources/write-small-business-website-brief", "/resources/how-long-to-build-small-business-website", "/resources/should-business-own-domain", "/how-it-works"],
  },
  {
    path: "/resources/write-small-business-website-brief",
    title: "How to Write a Website Brief for a Small Business",
    metaTitle: "How to Write a Small-Business Website Brief",
    metaDescription: "Use this practical website-brief framework to define goals, customers, pages, content, features, responsibilities, constraints and approval before a build.",
    eyebrow: "Website brief template",
    heading: "Describe the decision the website must support—not just the style you like.",
    intro: "A useful website brief is short enough to be read and specific enough to expose assumptions. It gives the designer context without pretending the business must solve the design before hiring them.",
    quickAnswer: "A small-business website brief should cover the business, audience, current problem, desired customer action, services, proof, required pages, features, content ownership, technical accounts, constraints, approver and launch priorities. Separate must-haves from later ideas so the quote stays meaningful.",
    kind: "guide",
    updated,
    published,
    sections: [
      { title: "1. Business and project summary", paragraphs: ["Write two or three plain sentences describing what the business does, where it operates and why the website project is happening now. Include the current site or profiles and state what is not working.", "Avoid positioning language that nobody in the business can explain. A designer needs the commercial reality before refining the public message."], },
      { title: "2. Audience and primary action", bullets: ["Who is the priority visitor?", "What situation brings them to the site?", "What do they need to understand before trusting the business?", "What should they do next: call, WhatsApp, book, buy or request a quote?", "How does the business actually respond after that action?"], },
      { title: "3. Scope and content", paragraphs: ["List the pages you believe are required, but explain the purpose of each. A page called Services is less informative than ‘help prospects compare residential and commercial packages before calling.’", "For every page, identify who supplies the copy, photography, logo, credentials and approvals. Mark missing material rather than pretending it will appear during development."], },
      { title: "4. Features and integrations", bullets: ["Contact or qualification form", "Call and WhatsApp actions", "Map and location information", "Booking or calendar", "Payments or ecommerce", "Content management", "Analytics and consent", "Email, CRM or other integrations"], paragraphs: ["Name existing platforms where possible. ‘Add booking’ is not enough if the team has not decided which calendar controls availability or who handles cancellation."], },
      { title: "5. Constraints, ownership and approval", paragraphs: ["Record launch deadlines that have a real business reason, accessibility or language needs, legal review, brand constraints and the final approver. Distinguish the must-launch scope from future phases.", "State that the business expects control of the domain, hosting and agreed website assets after final payment. Confirm revision rounds, handover and third-party costs before production begins."], },
      { title: "Copy-and-fill brief outline", bullets: ["Business: [what you do, where and for whom]", "Problem: [what the current presence fails to do]", "Primary visitor: [priority customer]", "Primary action: [call / WhatsApp / book / buy / enquire]", "Required pages: [page + purpose]", "Required features: [feature + business workflow]", "Content owner: [who supplies and approves each asset]", "Must launch with: [non-negotiables]", "Later phase: [useful but not required now]", "Final approver: [one named role or person]"], },
    ],
    faqs: [
      { question: "How long should a website brief be?", answer: "For a small business, one to three focused pages can be enough. Complexity should come from the project, not from a template demanding unnecessary detail." },
      { question: "Should the brief include a budget?", answer: "A realistic range helps the designer recommend an appropriate scope. It is also useful to separate the build budget from domain, hosting, media and ongoing tools." },
      { question: "Do I need to choose the technology?", answer: "Usually no. Describe the requirements, existing systems and ownership needs. The provider should recommend technology and explain the trade-offs." },
      { question: "Can the brief change after the project starts?", answer: "Yes, but a meaningful change to pages, features or direction may affect the quote and schedule. Use a documented change request instead of treating it as an invisible revision." },
    ],
    relatedPaths: ["/resources/prepare-before-hiring-web-designer", "/how-it-works", "/website-ownership", "/pricing"],
  },
  {
    path: "/resources/website-more-calls-whatsapp-enquiries",
    title: "How Can a Local-Business Website Generate More Calls and WhatsApp Enquiries?",
    metaTitle: "Get More Calls & WhatsApp Enquiries From a Website",
    metaDescription: "Improve calls and WhatsApp enquiries with clearer intent, mobile actions, service and location context, credible proof, useful forms and consented analytics.",
    eyebrow: "Enquiry-path guide",
    heading: "Make contact easier—but first make the decision feel safer.",
    intro: "Adding a floating WhatsApp button does not repair an unclear offer. A visitor contacts a business when the page answers enough of the decision and the next step feels appropriate for their situation.",
    quickAnswer: "To increase useful calls and WhatsApp enquiries, state the service and area clearly, show relevant proof, answer price and process questions, place mobile-friendly contact actions near decision points, prefill a helpful WhatsApp message and measure completed actions with consent. No layout can guarantee lead volume or quality.",
    kind: "guide",
    updated,
    published,
    sections: [
      { title: "Begin with intent clarity", paragraphs: ["The first screen should help the right visitor recognise that the business solves their problem and serves their area. A contact button cannot compensate for an opening message that could belong to any company.", "Use the words customers understand. Name the service, location when relevant and what happens after contact. Avoid forcing someone to message just to discover basic eligibility."], },
      { title: "Put each contact method where it fits", bullets: ["Call for urgent or conversation-heavy needs", "WhatsApp for quick context, images or asynchronous follow-up", "A structured form for quotations that need several details", "Booking for genuinely available time slots", "Email as a visible alternative for formal or non-urgent enquiries"], paragraphs: ["Choose one primary action per page and keep other appropriate options available. Five equally loud buttons make the visitor decide how the business works before deciding whether to contact it."], },
      { title: "Improve the WhatsApp handoff", paragraphs: ["A prefilled message can identify the page or service: ‘Hi, I am asking about the kitchen-renovation service on your website.’ That is more useful than a generic hello and helps the team reply with context.", "Do not prefill sensitive information, make unsupported promises about response time or add visitors to marketing lists without consent. The website should state when the channel is monitored."], },
      { title: "Earn the action with relevant proof", bullets: ["Original project, product or facility images", "Accurate team and qualification information", "Genuine testimonials with permission", "A transparent process", "Location, hours and service coverage", "Useful answers to price, timing and preparation questions"], },
      { title: "Measure the path, not private messages", paragraphs: ["Analytics can record a click to call, click to WhatsApp or successful form submission. It should not send phone numbers, names, message contents or other personally identifiable information to Google Analytics.", "A click is not automatically a qualified lead, and a lead is not automatically revenue. Review call quality and operational response alongside the website events before changing the page."], },
      { title: "Common friction to remove", bullets: ["Phone numbers that are not tappable", "WhatsApp links that open the wrong account", "Forms that ask for unnecessary information", "No confirmation after submission", "Contact actions hidden only in the footer", "Unclear service area", "Slow mobile pages", "Buttons promising booking when the business only accepts requests"], },
    ],
    faqs: [
      { question: "Should every page have a WhatsApp button?", answer: "Only when WhatsApp is an appropriate and monitored route. The action can repeat at sensible decision points without covering content or becoming the only way to learn basic information." },
      { question: "Can a website guarantee more calls?", answer: "No. Demand, visibility, competition, offer quality, reputation and response handling all affect enquiries. The website can improve clarity and reduce contact friction." },
      { question: "What should a contact form ask?", answer: "Ask only what helps the next response: identity, contact route and essential project context. Explain why sensitive details are needed and avoid collecting information the business cannot protect." },
      { question: "How do I know which CTA performs better?", answer: "Track consented CTA events and successful form submissions, then compare them with lead quality. A high click count can still be poor if the message or response process attracts the wrong enquiries." },
    ],
    relatedPaths: ["/resources/local-business-website-sections", "/industries/home-services", "/how-it-works", "/free-website-demo"],
    sources: [{ label: "Google Analytics: Avoid sending personally identifiable information", url: "https://support.google.com/analytics/answer/6366371" }],
  },
  {
    path: "/resources/landing-page-vs-website-small-business",
    title: "Landing Page vs Website for a Small Business",
    metaTitle: "Landing Page vs Website for Small Business | Project Monet",
    metaDescription: "Compare a landing page and full website by purpose, traffic source, search visibility, cost and customer journey so your small business chooses the right scope.",
    eyebrow: "Website scope decision",
    heading: "Choose one focused action—or a place customers can properly explore.",
    intro: "A landing page and a business website can look similar on the first screen, but they solve different problems. The useful choice depends on where visitors come from, how much they need to understand and whether the page supports one campaign or the business's broader online presence.",
    quickAnswer: "Choose a landing page for one campaign, one audience and one measurable action, especially when traffic comes from an advertisement, email or specific promotion. Choose a full website when customers need to discover, compare and trust several services, people, locations or proof points. Many businesses eventually use both.",
    kind: "guide",
    published: "2026-08-28",
    updated: "August 28, 2026",
    modified: "2026-08-28",
    sections: [
      { title: "The practical difference", paragraphs: ["A landing page is a focused destination built around one offer and one next step. It usually reduces navigation and removes unrelated choices so a visitor can act on the promise that brought them there.", "A business website supports a wider journey. It gives customers routes to learn about the company, compare services, review work, understand policies and return later through search or a direct visit."] },
      { title: "When a landing page is the better starting point", bullets: ["One advertisement or outreach campaign", "One event, launch, consultation or downloadable offer", "One audience with a specific problem", "A short decision that does not require several service pages", "A clear conversion event such as a qualified form, booking request or purchase"], paragraphs: ["The page still needs accurate information, mobile usability, privacy handling and enough proof for the decision. Fewer links do not justify hiding material terms or forcing every visitor into a form."] },
      { title: "When a full website earns its extra scope", bullets: ["Customers search for several distinct services or questions", "The business has practitioners, locations, projects or products to compare", "Trust depends on an about page, policies, process or detailed proof", "Organic search and repeat visits matter", "Different visitors need different contact or enquiry paths"], paragraphs: ["A full website does not need dozens of pages. A focused small-business site may begin with Home, Services, About, Work and Contact, then expand only when a genuinely separate customer or search decision appears."] },
      { title: "Landing page, one-page website and homepage are not the same thing", paragraphs: ["A one-page website can contain the complete public presence of a focused business, including its navigation, services, proof and contact information. A homepage is the entry page of a broader website and routes visitors into other pages. A landing page is normally isolated around one campaign action.", "The labels are often used loosely in quotes. Ask what the page must do, which navigation it includes, where traffic will come from and what happens after the visitor acts."] },
      { title: "How to decide without overbuilding", bullets: ["List the exact traffic source", "Name the visitor and the one decision they are making", "Write the questions that must be answered before action", "Separate campaign information from permanent business information", "Choose the smallest structure that answers those questions credibly", "Plan how the page will be measured and maintained"] },
      { title: "How Project Monet scopes the two", paragraphs: ["Project Monet's Starter Website begins at ₹20,000 in India or $299 internationally for a focused one-page business presence. A campaign landing page or a larger multi-page website is quoted against its actual content, integrations and operating requirements.", "The free homepage concept can help an eligible business assess the visual direction before the paid scope begins. It is a preview, not a finished landing page or free production website."] },
    ],
    faqs: [
      { question: "Can a landing page replace a business website?", answer: "It can be enough for one focused campaign or an early offer. It is usually a weak replacement when customers need several services, company information, policies, proof or organic search content." },
      { question: "Is a one-page website a landing page?", answer: "Not necessarily. A one-page website can be the complete navigable presence of a business, while a landing page is usually a campaign destination with one conversion goal." },
      { question: "Which is better for SEO?", answer: "A full website has more room for distinct, useful search pages. A landing page can still be indexed, but campaign pages are often narrow and should not be multiplied into near-duplicates merely to target keywords." },
      { question: "Can I run ads to my normal homepage?", answer: "You can, but a focused landing page may match a specific advertisement more closely. The right destination depends on the ad promise and how much context the visitor needs." },
      { question: "Can a landing page become part of the website later?", answer: "Yes. Preserve the useful content and canonical strategy, then integrate or redirect it carefully when the campaign or site structure changes." },
    ],
    relatedPaths: ["/services/web-design-for-local-businesses", "/resources/one-page-vs-multi-page-website", "/resources/small-business-website-cost-india", "/pricing", "/free-website-demo"],
    sources: [{ label: "Google Ads: Understanding landing page experience", url: "https://support.google.com/google-ads/answer/2404197" }],
  },
  {
    path: "/resources/web-design-agency-vs-freelancer-india",
    title: "Web Design Agency vs Freelancer in India",
    metaTitle: "Web Design Agency vs Freelancer in India | Project Monet",
    metaDescription: "Compare a web design agency and freelancer in India by scope, communication, continuity, ownership, support and total cost—not the label or headline price.",
    eyebrow: "Provider comparison",
    heading: "Choose the working model that fits the risk—not the label on the proposal.",
    intro: "A skilled freelancer can outperform a poorly organised agency, and a capable agency can cover work that one person cannot sustain. The useful comparison is not freelancer versus agency in the abstract; it is the actual people, responsibilities, process and handover behind your project.",
    quickAnswer: "Hire a freelancer when the scope is focused, direct communication matters and one capable person can own the work. Choose an agency when the project needs several disciplines, parallel delivery or formal support coverage. In either case, compare named deliverables, relevant work, ownership, access, revision limits, recurring costs and post-launch responsibility.",
    kind: "guide",
    published: "2026-08-28",
    updated: "August 28, 2026",
    modified: "2026-08-28",
    sections: [
      { title: "Start with the scope and failure points", paragraphs: ["A focused brochure website may need strong design, clear copy structure and reliable development from one experienced builder. A multilingual store with photography, catalogue migration, payments, analytics and ongoing campaigns may need several specialists.", "List the work that must happen simultaneously, the decisions that require specialist review and the consequences if one person becomes unavailable. That reveals whether a larger team is genuinely useful."] },
      { title: "Where a freelancer can be a strong fit", bullets: ["Direct communication with the person doing the work", "A focused scope with limited dependencies", "Faster decisions when one person owns design and build", "Lower overhead when the project does not need a large team", "Continuity with one hands-on specialist who understands the site"], paragraphs: ["Ask how holidays, illness, urgent support and specialist gaps are handled. The answer matters more than assuming every freelancer is flexible or every agency is always available."] },
      { title: "Where an agency can justify the additional structure", bullets: ["Several disciplines are required at the same time", "The organisation needs procurement, reporting or formal support processes", "The project includes substantial content, commerce, data or integrations", "Multiple stakeholders need coordinated workshops and approvals", "Ongoing delivery needs coverage beyond one person's capacity"], paragraphs: ["Confirm who will actually work on the account. A large sales presentation does not guarantee senior day-to-day attention, and a bigger team can create communication overhead if roles are unclear."] },
      { title: "Compare total cost, not only the build quote", bullets: ["Defined pages, features and content responsibilities", "Revision rounds and change-request rates", "Domain, hosting, software and licence costs", "Maintenance or support minimums", "Migration, cancellation and handover terms", "Who owns the code, design, content and accounts after final payment"], paragraphs: ["A cheaper quote can be the right choice when the scope is genuinely smaller. It becomes expensive when essential work is excluded, the business lacks account access or a future provider cannot continue without rebuilding everything."] },
      { title: "Questions to ask either provider", bullets: ["Who is responsible for design, development, copy and testing?", "Which relevant projects can I inspect directly?", "What is excluded from the quote?", "Who controls the domain, hosting and analytics accounts?", "How are delays, feedback and out-of-scope requests handled?", "What exactly is handed over after final payment?", "What support exists after launch, and is it optional?"] },
      { title: "Where Project Monet fits", paragraphs: ["Project Monet is a focused website studio led by Mayank Harsh, not a large full-service agency. The hands-on model suits local and small businesses that value direct design and development ownership, a defined scope and optional maintenance.", "The right answer is still allowed to be another provider. A project that needs a large content operation, complex custom software or specialist regulated review should be scoped honestly before either side commits."] },
    ],
    faqs: [
      { question: "Is a freelancer always cheaper than an agency in India?", answer: "No. Rates depend on experience, demand and scope. Compare the same deliverables, support, licences and ownership terms before treating two headline prices as equivalent." },
      { question: "Is an agency safer for a business website?", answer: "Not automatically. Safety depends on contracts, access control, backups, documentation, technical quality and continuity. A capable freelancer can provide these, while an agency can still have weak processes." },
      { question: "Who should own the domain and hosting?", answer: "The business should normally control the accounts and recovery details, while granting the provider the access needed to work. The handover should document both." },
      { question: "Can I hire a freelancer and specialists separately?", answer: "Yes. A lead freelancer or studio can coordinate trusted specialists when roles, fees, confidentiality and approvals are clear." },
      { question: "What proof should I request?", answer: "Inspect live relevant work, ask which parts the provider completed, and distinguish client results from speculative concepts. Do not rely only on screenshots or unverified performance claims." },
    ],
    relatedPaths: ["/services/web-design-for-local-businesses", "/resources/prepare-before-hiring-web-designer", "/resources/small-business-website-cost-india", "/website-ownership", "/free-website-demo"],
  },
];
